### ISSUE TITLE
Twivey Report UI

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#101]
![001](https://cloud.githubusercontent.com/assets/7436116/7508643/79358c02-f4a1-11e4-99c7-5d9197570d62.jpg)
![003](https://cloud.githubusercontent.com/assets/7436116/7508652/b68807ba-f4a1-11e4-8fad-a0cdd9818923.jpg)

are these two screenshots of one report? or two different reports.
if one report then what is at end of first screen shot and what is at start of second screenshot
these are final bill report UI, would you please send me drafted bill report UI.

**Comment by mnarewec** [comment]
(1) One Report.
(2) Refer image , i.e red rectangle indicating the header/footer section
(3) Draft Bills will be the same as FINAL BILLS but will not be printed together with the remittance form. It should have the text 'DRAFT BILL' shown clearly on the header.

![001](https://cloud.githubusercontent.com/assets/10192106/7510964/afd4a426-f4e4-11e4-9fda-652000a23ae6.jpg)

![003](https://cloud.githubusercontent.com/assets/10192106/7510970/bac05fa6-f4e4-11e4-8743-a779edcaf016.jpg)

**Comment by jmervana** [comment]
@mnarewec 
What is street address?
whose postal address is there in footer of 1st page?

**Comment by mnarewec** [comment]
(1) Street Address is the same as Location/Physical Address
(2) Postal Address on the footer is the Law Firm's Postal Address
(3) Hide Units Option - You image is correct (
(4) Hide Rate Option - Your image is incorrect. It should be the Lawyer's Rate that is hidden (Timesheet)
(5) Hide Totals Option - Same as Unit and Rate. It should be the timesheet Totals.
(6)  Professional Rate Summary Bradshaw Template, there is a section of the report at the end of timesheet totals that state the Lawyers Totals. That's the page
(7). [Ending Pay Period Date] - immm. Ok the text should now read "To our cost and incidentals as at [Period End Date] with respect to the following:

**Comment by mnarewec** [comment]
(1) Street Address is the same as Location/Physical Address
(2) Postal Address on the footer is the Law Firm's Postal Address
(3) Hide Units Option - You image is correct (
(4) Hide Rate Option - Your image is incorrect. It should be the Lawyer's Rate that is hidden (Timesheet)
(5) Hide Totals Option - Same as Unit and Rate. It should be the timesheet Totals.
(6)  Professional Rate Summary Bradshaw Template, there is a section of the report at the end of timesheet totals that state the Lawyers Totals. That's the page
(7). [Ending Pay Period Date] - immm. Ok the text should now read "To our cost and incidentals as at [Period End Date] with respect to the following:

**Comment by mnarewec** [comment]
@jmervana , unable to test because of issue in #108

**Comment by mnarewec** [comment]
(1) Logo is not 100% position/align as per the images provided to you

![image](https://cloud.githubusercontent.com/assets/10192106/7782586/84b64256-0162-11e5-8ec4-8b0c3c4b344c.png)

**Comment by mnarewec** [comment]
@jmervana refer inconsistencies between the Twivey Orginal format and the one you did.

![finalbills 15-05-2015 1 _001](https://cloud.githubusercontent.com/assets/10192106/7791544/528dcec8-02e5-11e5-8e2b-fc319b8cf912.png)
![finalbills 15-05-2015 1 _002](https://cloud.githubusercontent.com/assets/10192106/7791545/55949ebc-02e5-11e5-8869-19c17101760c.png)
![finalbills 15-05-2015 1 _003](https://cloud.githubusercontent.com/assets/10192106/7791547/58633f04-02e5-11e5-9a61-2ee78cce7257.png)

**Comment by jmervana** [comment]
@mnarewec 
change format of unit , what should I display instead of 0.1?
currency sign is there on each and every amount


see screen shot and correct me if any mistake

Draft Bill

![image](https://cloud.githubusercontent.com/assets/7436116/7795913/4a7e9c28-02f7-11e5-82c9-22e2ef68ad88.png)

Final Bill 

![image](https://cloud.githubusercontent.com/assets/7436116/7795975/efba05c4-02f7-11e5-8d29-c6349e1490dd.png)


Remittance Slip

![image](https://cloud.githubusercontent.com/assets/7436116/7795990/26e40c52-02f8-11e5-8a92-6e42b346535a.png)

**Comment by mnarewec** [comment]
(a) I think currency sign is related to the PDF printing funny characters issue I raised earlier. It is showing on my machine but not on the client machine

(2) Format change for Units is only for TWIVEY FORMAT bills.
0.1 =01
1.0 =10
0.3=03
4.5=45
etc

**Comment by jmervana** [comment]
@mnarewec 
b) done

**Comment by mnarewec** [comment]
Still issues in twivey format. Refer image below. Please urgently resolve @jmervana

**Comment by jmervana** [comment]
@mnarewec 
please upload image here

**Comment by mnarewec** [comment]
Image uploaded.

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
(1) In the Bills Default Page, if I select Twivey Format, and tick all options under Bills options (Lawyers Intials,Units, Rate, Total, Professional Time Summary), on Exporting to PDF, it is NOT showing the (1) Total and (2) Professional Time Sumary.

**Comment by jmervana** [comment]
@mnarewec 
there is no proffessional time summary in twivey report format

**Comment by AAndharia** [comment]
test

**Comment by mnarewec** [comment]
Will raise sets of changes to Twivey format in new issue
