### ISSUE TITLE
remmitance slip

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#102]
![002](https://cloud.githubusercontent.com/assets/7436116/7508685/66ba9f80-f4a2-11e4-9a34-1ec4429630a7.jpg)

we are not fetching bank address at company page and this slip contains bank address. what should be display instead?

**Comment by mnarewec** [comment]
Good question, Please create an extra field on The company setup page, as Bank Address. If there is a "," (Comman) then it will indicate a line break, just like how the Client Address is presented on the Bill

**Comment by mnarewec** [comment]
@jmervana Unable to test because of issue in #108

**Comment by mnarewec** [comment]
This item is confirmed done.
