### ISSUE TITLE
Company Setup - Add Bank Section

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#103]

**Comment by mnarewec** [comment]
@jmervana unable to see the Company Information under setup eventhough in roles, I have given access to Add/Edit/View company information. So unable to test.

**Comment by jmervana** [comment]
@mnarewec 
I have to check it at your side because I can see that under setup at my side. if you want I can saw you.

**Comment by mnarewec** [comment]
This is resolved.
