### ISSUE TITLE
Timesheet Page

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#106]
"There should be option to show time sheet entries by Files too. If it is shown by Files then in place of File Number on current List View page, show the Initials Lawyer."

**Comment by mnarewec** [comment]
(1) View by File - Add Timesheet Entry - File should be the first field and its number should be defaulted.

**Comment by AAndharia** [comment]
@mnarewec  - this will be a CR. If you agree, we'll estimate. Please confirm.

**Comment by mnarewec** [comment]
OK please estimate

**Comment by mnarewec** [comment]
@jmervana ,cc @AAndharia The requirement below is not captured. Please expedite

![image](https://cloud.githubusercontent.com/assets/10192106/7759150/603b832a-0052-11e5-8f50-3326ba6c26e6.png)

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
This requirement is not approved yet in CR7 sheet

**Comment by AAndharia** [comment]
@mnarewec - CR was estimated earlier, but not approved by you in the CR sheet and hence was not part of CR7. Please let us know if you need this now.

**Comment by mnarewec** [comment]
@AAndharia , I thought I approved this CR. Anyway,  I approve the change. Please proceed with the Change.

**Comment by mnarewec** [comment]
OK I just approve this CR.

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
@jmervana this issue is not implemented in v1.7.9

**Comment by jmervana** [comment]
@mnarewec 
1st is done
2nd is CR

**Comment by mnarewec** [comment]
(1) 1st is not done yet
(2) OK I approve CR
![image](https://cloud.githubusercontent.com/assets/10192106/7993219/1f855ce2-0b48-11e5-9d12-a6d3372d2c71.png)

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
@jmervana , the file owner should be defaulted and users should be able to remove it if the entry does not be for the file owner but for other lawyers. For example, if Robert is the File Owner, then it should be defaulted or selected first. Other lawyers can be added to. Robert can be remove from the list if he is not part of the entry.

**Comment by mnarewec** [comment]
Will close this and only work issue #130
