### ISSUE TITLE
Disbursement Page

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#107]
"There should be option to show Disbursement sheet entries by Files too. If it is shown by Files than in place of File Number on current List View page, show the Initials of Files’ Owner (Lawyer)"

**Comment by mnarewec** [comment]
(1) View by Disbursement Type  - Add Disbursement Entry - The unit Rate is not defaulted AND read only as it should be.

(2)View by Files - Add Disbursement Entry. - (a) File Number should be the first field, and defaulted from the selection and should be read only. (b) Unit Rate should be defaulted and Read only as in (1).

**Comment by AAndharia** [comment]
@mnarewec  - 2 above will be a CR. If you agree, we'll estimate. Please confirm.

**Comment by jmervana** [comment]
@mnarewec 
unit rate is depending on disbursement rate type if it is fixed than readonly otherwise user can change it and it is defaulted.

3rd point is done

**Comment by mnarewec** [comment]
Ok please estimate and proceed with CR

**Comment by mnarewec** [comment]
Ok I just approve this CR.

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
@jmervana , this is not implemented as expected especially in the 'View by File' mode pop up window
(1) File Number should be the first field and it should be read only,
(2) Order the tab, correctly.

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
This is done.
