### ISSUE TITLE
Bill Generation –  Creation of Batch  for Bills

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#108]
"Include a new amount field in the Batch Header, ‘Minimum WIP Amount’. Depending on this field ONLY Files with WIP equal or above that amount will be selected for Bill Generation."

"Include a new field ‘Lawyers’ - this will capture the Files of the selected lawyers to be used in the generation of Bills. Single, Multiple or All users can be selected."

"Creation of Batches according to Lawyers. A user can create a batch based on ALL Lawyers or Selected Lawyers. That means a new Batch can be created for a Lawyer whose files has not been selected in a Batch yet. That means you can have one or more draft batches."

Update Batch – should have options to select/unselect lawyers as well as the Minimum WIP amount

"When generating Bills or updating Bills, the Billing Batch records should be already sorted form Big WIP amount to Small WIP Amount."

New Option to ‘Delete Batch’ - Batch can ONLY be deleted if it is at initial or draft stage. Final Batch cannot be deleted.

"For fixed rate files, the Total WIP Amount is not calculated, therefore it is shown on the Bill Generation Files selection view as zero. Now we would like the Fixed Rate value to show there in place of zero."

**Comment by mnarewec** [comment]
Nothing is showing. Got this runtime error.
![image](https://cloud.githubusercontent.com/assets/10192106/7668164/caeffd7a-fc6c-11e4-9710-7b1164f2079a.png)

**Comment by jmervana** [comment]
@mnarewec 
I cannot reproduce this error. how did you get this error? OnpageLoad or On any Action?

**Comment by mnarewec** [comment]
On Page Load.

**Comment by jmervana** [comment]
@mnarewec 
as we discussed , this error is not reproduced now.

**Comment by mnarewec** [comment]
(1) When deleting a batch, it should atleast prompt user to confirm deletion

**Comment by mnarewec** [comment]
(2) After Running Bills of two Batches, the 1st page did not show the list of Files Process but it did show the bills generated
![image](https://cloud.githubusercontent.com/assets/10192106/7759469/0be92d56-0055-11e5-8dee-6ccc89e208f4.png)

![image](https://cloud.githubusercontent.com/assets/10192106/7759488/2a57467e-0055-11e5-8590-0278d2b030d6.png)

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
(1) This issue '"For fixed rate files, the Total WIP Amount is not calculated, therefore it is shown on the Bill Generation Files selection view as zero. Now we would like the Fixed Rate value to show there in place of zero." this CR is not implemented.

(2) Also I noticed that 'DRAFT' Bills have invalid value. It seem to duplicate the rate, in the value column. Please check for BOTH (Bradshaw & Twivey) Format.

(3) After running DRAFT bills, and then you un-check a file(s), and you then you ran FINAL without running DRAFT again, all the files including those un-checked, have FINAL bills generated. This is not right. To avoid this, if a  bill is unchecked/or checked during draft bills, then Hide the FINAL button. This will force the user to run DRAFT Bills again.

**Comment by jmervana** [comment]
@mnarewec 
1. if file is fixed and there are two entries in timesheet table for this then timesheet rate for this file is twice a fixed rate amount or one time fixed rate amount.
in report , should I display fixed rate amount as a timesheet amount?

2nd point, I cannot get you here.

3rd point is already handle if user uncheck checkbox final bill will not be generated for that entry if user don't run draft.

**Comment by mnarewec** [comment]
(1) If you have source for v1.6 then please check and confirm this rule. For fixed rate file, the Total Professional Time (Total Timesheet Time value) is NOT the sum of all timesheet entries but it is the Fixed Rate Amount.

(2) I think it is only appears on Twivey Bill Report (please check the images I attached for issue #101

**Comment by jmervana** [comment]
@mnarewec 
for the first point , now we have multiple lawyer selection, if file is fixed rate and there are 3 lawyers selected whats the entry total?

**Comment by jmervana** [comment]
@mnarewec 
Done as we discussed on gmail.

**Comment by mnarewec** [comment]
Fixed Rate issue is not resolved @jmervana

**Comment by jmervana** [comment]
@mnarewec 
Would you please explain what should not be done?

**Comment by mnarewec** [comment]
Billing Reports are showing correct value. This issue will be raised separately.
