### ISSUE TITLE
"Bills Printing  Defaults Page"

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#109]
Create a new setup feature/page for Bills Printing Defaults. 
It should have 
option to use Bill Format of Bradshaw or Twivey  (Default Bradshaw)
Option to select the Font Style on the PDF Bill.   (Default Calibri )
Option to whether Print Remittance Slip together with FINAL Bills (Default Not to Print)

It should also have option whether to show or hide following columns
Line Lawyers Initials (Default Not Show)
Line Units (time) (Default Show)
Line Rate (Default Show)
Line Total (Default Show)
Show Professional Time Summary (Default Show)

**Comment by mnarewec** [comment]
This is achieved.
