### ISSUE TITLE
New Bills Format

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#110]
"Create a new Bill Layout to reflect current Twivey Lawyers Fee Note Layout (100% exact). The Bill includes a remittance slip as its last page. Refer attached is the sample 2 page bill, 3rd page is the remittance slip."

"When printing Final or Draft Bills it should pop up with the setup Bills printing prompts, the default will be as per Bill setup page, but option to choose different option."

**Comment by mnarewec** [comment]
@jmervana ,cc @AAndharia This is the same requirement as #101 ??

**Comment by mnarewec** [comment]
@jmervana , unable to test because of issue in #108

**Comment by mnarewec** [comment]
(1) 'Bills Printing Properties' page shown when 'Show Bill Printing Defaults' at the time of export but nothing is happening,

**Comment by jmervana** [comment]
@mnarewec 

4th point  - Free Note No. contains bill number which is generated on final bill, what should I write in Free Note Number in draft bill?

3rd point  - in Cr sheet , it is mentioned that 100% match to Twivey Lawyers Report images , so I put footer same as in images.

2nd point - see video - for draft bill export - http://screencast.com/t/gcgpYir0f
2nd point - see video - for final bill export -  http://screencast.com/t/TqKViPCsKP3e

for the first point you can see both videos mentioned above you can see popup will close after press ok and bills are generated.

**Comment by mnarewec** [comment]
(1) Logo is not 100% position/align as per the images provided to you

![image](https://cloud.githubusercontent.com/assets/10192106/7782586/84b64256-0162-11e5-8ec4-8b0c3c4b344c.png)

(2) When exporting Draft Bills, the File Name is still 'viewproof'

**Comment by mnarewec** [comment]
This issue will be deal with in issue #101
