### ISSUE TITLE
"New Report -  Closed Files Listing"

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#111]
"New Report to show list of close files. 
The fields to show includes  
FIle Number, 
Client Name, 
Subject Matter, 
Lawyer, 
Date Instructed, 
Closed File Number, 
Date Closed, 
CLosed File Box Number, 
Closed Reason.

Sorted by File Number"

**Comment by mnarewec** [comment]
This is achieved. Thanks.
