### ISSUE TITLE
File Ledger Report

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#112]
"New Report to show details of a File. Details of a File Includes
Client Contactable Information
File Subject Matter and Lawyer Responsible (Instructed Date, etc)
Current WIP – Detail Listing of WIP Timesheet Entries for the File
Current Disbursements – Detail Listing of Disbursement Entries for the File
Listing of Outstanding Bills
Listing of Trust Fund Transactions and Balance

Each items above will form a section of the report. The Report should show the data selection popup like the client 
statement report,this time it’s Files instead of customers. Place this report under section ‘Clients’ on report home page."

**Comment by mnarewec** [comment]
Refer to the image for correction 

(5) File Ledger - Refer attachments for modification
![file ledger report - kumulsoft billing system_001](https://cloud.githubusercontent.com/assets/10192106/7666340/6b8f23de-fc25-11e4-94ad-2b11e84b937c.png)

![file ledger report - kumulsoft billing system_002](https://cloud.githubusercontent.com/assets/10192106/7666345/81fec840-fc25-11e4-841c-8c30c52fcf73.png)

![file ledger report - kumulsoft billing system_003](https://cloud.githubusercontent.com/assets/10192106/7666359/c8b92424-fc25-11e4-83f6-a56c623b0bb4.png)

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
There will be some additional requirements for this report but will treat this has closed first.
