### ISSUE TITLE
Create System Default Page

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#113]
"Create a feature to Record System Defaults. Its first Field will be ‘Show Bills Printing Defaults’ (Check or Unchecked) – if checked then during Printing of Draft/Final Bills the ‘Bills Setup will show."

"Show dash in file numbers" (checked or unchecked) - if checked file number should be 
14-0001/2014-0001  or  140001/20140001

**Comment by mnarewec** [comment]
(1) Create an additional field called 'Database backup Directory' and show folder browse for user to select a directory on the server.

**Comment by jmervana** [comment]
@mnarewec 

As per my understanding, you want user to select directory for database backup, is it?
if yes then what should I do if user not select path and try to take backup of database?

**Comment by AAndharia** [comment]
@mnarewec - if we have to allow a user to select a location from server, this will be a CR. Please confirm.

**Comment by mnarewec** [comment]
@jmervana cc @AAndharia  Please ignore that requirement for a while.
