### ISSUE TITLE
Changes to Reports

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#114]
"Aged work in Progress by Clients – Like Statement Report show the Client Selection Page. Include a Close button on the Report to revert to Reports Home Page"

"Aged Work In Progress By Lawyers - Like Statement Report show the Lawyers Selection Page. Include a Close button on the Report to revert to Reports Home Page"

"Aged Billing Details - Like Statement Report show the Client Selection Page. Include a Close button on the Report to revert to Reports Home Page"

"Outstanding Bills Details - Like Statement Report show the Client Selection Page. Include a Close button on the Report to revert to Reports Home Page"

"Lawyers Report – Show totals of 12 rotating months like what we did for Dash Board Outstanding Bills Graph. Show Close button to Revert to home"

"Client edger - Like Statement Report show the Client Selection Page. Include a Close button on the Report to revert to Reports Home PageAlso include option to list Closed Files Only, Active Files Only or Both. Default should be Ative Files."

Client Statement – Include Close Button to revert to home

Outstanding Bills Summary – include close button to revert to home

Aged Billing Summary – include close button to revert to home.

Draft Billing - Making UI same as reports under Reports menu

Final Billing - Making UI same as reports under Reports menu

File Report - Making UI same as report under Reports menu

Modification in pdf for final bill

Modification in pdf for draft bill

**Comment by mnarewec** [comment]
(1) Aged work in progress by Client - When executing it is not showing client list but came up with following runtime error.
![image](https://cloud.githubusercontent.com/assets/10192106/7666314/9d12e798-fc24-11e4-8df1-0cd800bfe382.png)

**Comment by jmervana** [comment]
@mnarewec 
after execute dbscript I gave in #118 first four problem is resolved and 5th point is already done in #112

**Comment by jmervana** [comment]
@mnarewec 

I have sent you a mail with new dbscript.

**Comment by mnarewec** [comment]
This solves the issue.
