### ISSUE TITLE
"Menus and Home  Pages Changed"

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#115]
* Remove ‘Entries’ main menu but place its submenu items under Billing Menu
* Create a new Main Menu called ‘Bank’
* Move ‘Receipt Bills’ from Billing menu to ‘Bank’ Menu
* Move ‘Trust Funds’ menu item to ‘Management’ menu
* Like Reports, Create a Home Page for Management. It will have two sections: ‘Contacts’ and ‘Professional Billing’. Under Contact you place ‘Lawyers’ and ‘Clients’. And under ’Professional Billing’ you place ‘Files’,  ‘Disbursements’, and ‘Trust Fund’
* Like Reports, Create a Home Page for Setup. It will have two sections: ‘System’ and ‘Billing’. Under ‘System you place ‘Company ‘ and ‘Defaults’  under ‘Printing’ you will place ‘Bills Printing Defaults ’

**Comment by mnarewec** [comment]
(1) Under Billing, menus should be 'spelt' and ordered in the following order : Timesheet Entry, Disbursement Entry, Bill Generation, Outstanding Bills Search.

(2) Bank Menu should be renamed to 'Cash Book' and should be moved to between Billing and Management

(3) Under Management Menu renamed the following: Contacts = 'Manage Contacts', Professional Billing = 'Manage Billing'

(4) a. Under Setup Menu and System section rename the following : System Default Settings ='System Defaults' , Disbursement ='Disbursement Types'
    b. Company Information is missing in  System section.

(5)

**Comment by AAndharia** [comment]
@jmervana - please estimate and let me know if this is a CR.

**Comment by AAndharia** [comment]
@mnarewec - this will be a CR. Please let me know if you are interested to do, we can estimate.

**Comment by mnarewec** [comment]
OK Approve

**Comment by AAndharia** [comment]
@jmervana  - please take care of this.

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Done

**Comment by mnarewec** [comment]
Confirmed done.
