### ISSUE TITLE
Database Backup

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#116]
* any permission required for user to do this?Yes
* at which location backup will be taken? Obviously a location on the server
* what will be backup file name? Client Database Name + the Date & Time
* Create a new main menu Tools and create a page like ‘Reports’ page and put this  action item in the section ‘Database’

**Comment by mnarewec** [comment]
Backup to the 'Database backup directory' provided for in the System Settings.

**Comment by jmervana** [comment]
@mnarewec 

As per my understanding, you want user to select directory for database backup, is it?
if yes then what should I do if user not select path and try to take backup of database?

**Comment by mnarewec** [comment]
When the user take the backup, it will be backed up to the directory defined in 'System Default Settings' @jmervana

**Comment by AAndharia** [comment]
@mnarewec - if we have to allow a user to select a location from server, this will be a CR. Please confirm.

**Comment by mnarewec** [comment]
Please disregard this new cr for a while.
