### ISSUE TITLE
Setup Menu

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#117]
(1) Company Information not shown on the setup menu when  user with permission to Company Information Login. 
(2) All setup items not showing when admin login.

**Comment by jmervana** [comment]
1) I can see company information on setup page when I have permission to view company information.

2) admin access only company information page under setup and for that you have to run following dbscript on database

DECLARE @actionId int, @menuId int
SELECT @menuId = MenuId FROM AppMenu WHERE MenuName = 'Company Information'
		SELECT @actionId = ActionId FROM [dbo].[AppMenuAction] WHERE MenuId = @menuId AND [ActionName] = 'View'
		INSERT [dbo].[AppMenuActionAccess] ([ActionId], [RoleName]) VALUES (@actionId, N'DefaultUserRole')

**Comment by mnarewec** [comment]
@jmervana, That solves the Admin user problem but not the other users in other roles.

**Comment by jmervana** [comment]
@mnarewec 
I have to check it at your side. I can see all menus at my side

**Comment by mnarewec** [comment]
This issue is resolved.
