### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#118]
(1) Aged Outstanding Bills Summary - Amount missing.

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 

I can see amount on dashboard. see screen shot

![image](https://cloud.githubusercontent.com/assets/7436116/7665167/18c3ff5a-fbc9-11e4-8e20-835fbc4bcc84.png)

**Comment by mnarewec** [comment]
@jmervana , this is my screenshot
![image](https://cloud.githubusercontent.com/assets/10192106/7666118/3b7cb01c-fc1b-11e4-8204-b7b0973bcdff.png)

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
I am sorry marsh. there is a mistake in dbscript.
run following script to resolved this error.

DROP VIEW  dbo.vw_AgedBilling;
CREATE VIEW dbo.vw_AgedBilling
AS
SELECT     TOP (100) PERCENT dbo.MstClients.Name as ClientName,dbo.MstClients.Id as ClientId, dbo.MstFiles.FileNumber, dbo.MstFiles.SubjectMatter, SUM(CASE WHEN PeriodEndDate BETWEEN GetDate() 
                      - 31 AND GetDate() THEN TotalOutstanding ELSE 0 END) AS [Current], SUM(CASE WHEN PeriodEndDate BETWEEN GetDate() - 61 AND GetDate() 
                      - 30 THEN TotalOutstanding ELSE 0 END) AS [31-60 Days], SUM(CASE WHEN PeriodEndDate BETWEEN GetDate() - 91 AND GetDate() 
                      - 60 THEN TotalOutstanding ELSE 0 END) AS [61-90 Days], SUM(CASE WHEN PeriodEndDate < GetDate() - 90 THEN TotalOutstanding ELSE 0 END) AS [91 Days+], 
                      SUM(dbo.MstBills.TotalAmount) AS [Total Billed], SUM(dbo.MstBills.TotalOutstanding) AS [Total Outstanding], 
                      SUM(dbo.MstBills.TotalAmount - dbo.MstBills.TotalOutstanding) AS [Total Paid], dbo.MstFiles.DateInstructed, dbo.MstFiles.LawyerId
FROM         dbo.MstBills INNER JOIN
                      dbo.MstBillingBatch ON dbo.MstBills.BillBatchId = dbo.MstBillingBatch.Id INNER JOIN
                      dbo.MstFiles ON dbo.MstBills.FileId = dbo.MstFiles.Id INNER JOIN
                      dbo.MstClients ON dbo.MstClients.Id = dbo.MstFiles.ClientId
WHERE     (dbo.MstBills.Status = 1) AND (dbo.MstBillingBatch.Stage = 2) AND (dbo.MstFiles.FileStatus = 1) AND (dbo.MstClients.IsActive = 1)
GROUP BY dbo.MstClients.Name,dbo.MstClients.Id, dbo.MstFiles.FileNumber, dbo.MstFiles.SubjectMatter, dbo.MstFiles.DateInstructed, dbo.MstFiles.LawyerId
ORDER BY dbo.MstClients.Name
GO

**Comment by mnarewec** [comment]
This resolves the issue. Thanks
