### ISSUE TITLE
Final Bills & Draft Bills Totals  - on the Final Bill page not same as on the Bill Report

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#121]
Final Bill Page Total
![image](https://cloud.githubusercontent.com/assets/10192106/7757248/44d0e4ee-0044-11e5-98cb-77c5bcbecb32.png)

Bill Report
![image](https://cloud.githubusercontent.com/assets/10192106/7757338/d5483086-0044-11e5-9788-97366b58d0a5.png)

**Comment by mnarewec** [comment]
Did you resolve this issue @jmervana

**Comment by jmervana** [comment]
@mnarewec  
yes , it is resolved

**Comment by mnarewec** [comment]
Confirmed resolved.
