### ISSUE TITLE
Final Bills & Draft Bills Report 

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#122]
(1) When on view on the page, pressing cancel button must return them to Final Bills Page (if final bills) or Draft  Bills Page (if Draft Bills)

(2) Logo missing on Exported File (Both Draft and Final Report)
![image](https://cloud.githubusercontent.com/assets/10192106/7757518/6e707ef2-0046-11e5-8f81-6682f88e8590.png)

**Comment by jmervana** [comment]
![image](https://cloud.githubusercontent.com/assets/7436116/7765864/d5fea366-0080-11e5-8e84-d3c74c3d685f.png)

above screenshot is draft bill and contain logo after exported

![image](https://cloud.githubusercontent.com/assets/7436116/7765876/f524092a-0080-11e5-8ac7-ed7afccf974c.png)

above screenshot is final bill and contain logo after exported

**Comment by mnarewec** [comment]
Confirm this page is closed.
