### ISSUE TITLE
Random Text written on page

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#125]
(1) Refer this image
![image](https://cloud.githubusercontent.com/assets/10192106/7758870/591f99a2-0050-11e5-9c61-8b8e5aaf3578.png)

(2) and this one two , many more pages too
![image](https://cloud.githubusercontent.com/assets/10192106/7759018/63a96622-0051-11e5-80eb-1d85f9e24487.png)

**Comment by jmervana** [comment]
@mnarewec 
I cannot see any random text on any pages.

**Comment by mnarewec** [comment]
This is confirmed done.
