### ISSUE TITLE
Dashboard - 12 Monthly Outstanding Bills Graph

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#126]
No graphs. Just this error message
![image](https://cloud.githubusercontent.com/assets/10192106/7780338/d205ddba-0120-11e5-9dc1-82e3858904c5.png)

**Comment by jmervana** [comment]
@mnarewec 
this is done.

**Comment by mnarewec** [comment]
The issue still persist.

**Comment by jmervana** [comment]
@mnarewec 
try to clear your cache and run. because I cannot reproduce it again.
