### ISSUE TITLE
Billing Report (bradshaw format)

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#127]
Refer image.
![viewproof 2 _001](https://cloud.githubusercontent.com/assets/10192106/7813733/aaf2307e-0400-11e5-9e9a-15ea9733303a.png)

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
In the Bills Default Printing, Bradshaw Format, I did not check the show Lawyers initials, but it shows on Bills report. This should not be the case.

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
This is done.
