### ISSUE TITLE
Timesheet Entries (Fixed Rate File)

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#128]
When entering timesheet entries and the file type is Fixed rate file, Total charge is still calculating. Infact it should be zero,

**Comment by jmervana** [comment]
@mnarewec 
There is a changes in CR7 with following statement

**Comment by mnarewec** [comment]
@jmervana, You did not understand me correctly. There should be no change to the way fixed rate file is entered in timesheet. The only change I request for is in Bill Generation. When you created a Batch, it shows the File Number, Subject, WIP and Disbursement. Because WIP for Fixed Rate file is Always zero, I was thinking if on that view, you show the Fixed Rate Amount for that File.

**Comment by jmervana** [comment]
@mnarewec 
This is not reproduced

**Comment by mnarewec** [comment]
Correct. This issue is closed.
