### ISSUE TITLE
Changes in Billing Reports After Selection of multiple lawyers

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#129]
where should I display lawyer's initials (comma saperated) in draft bill / final bill for both (bradshaw & twivey)?

**Comment by mnarewec** [comment]
Same place as what you did for Twivey and Bradshaw currently. it must be for both Final and Draft Billing. The 'initials' option in Bills Printing Defaults will determine whether it shows on the Bills Report or not

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
This is done.
