### ISSUE TITLE
Remove dropdown from AddTimesheet Entry screen

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#130]
remove lawyer dropdown and set first selected lawyer in typehead as default lawyer.

**Comment by jmervana** [comment]
@mnarewec 
This will be CR, if you approve , we will estimate it.

**Comment by mnarewec** [comment]
OK approve. Not the first selected lawyer as the default but the owner of the file as the default lawyer.

**Comment by AAndharia** [comment]
@mnarewec  i've mentioned the estimated hours in the spreadsheet, considered this as approved and moving ahead implementing it.

**Comment by mnarewec** [comment]
I can't see the default Lawyer i.e. the file owner,

**Comment by jmervana** [comment]
@mnarewec 
where you cant see it.

**Comment by mnarewec** [comment]
In Timesheet Entry - View By File - Add Timesheet Entry - Pop up window

**Comment by AAndharia** [comment]
@jmervana - please let me know if this is implemented or need to be implemented?
