### ISSUE TITLE
Disbursement Entries - File Number Column Missing

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#132]
In the disbursement Entry main page - view by disbursement, the File Number column is missing. I don't know why you show Lawyer's initials here too. the instruction was, In the View by Files Mode, show Disbursement Type in the column.

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
@jmervana not yet. Refe image below
The highlighted column should be replaced by 'Disbursement type'
![image](https://cloud.githubusercontent.com/assets/10192106/7993395/37a6da98-0b49-11e5-9ca3-5793121c6872.png)

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
Confirmed resolved.
