### ISSUE TITLE
Bill Generation -Show Draft Bill error  for file '2015-0039'

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#133]
I am unable to print Draft Bills for a Particular File. Its coming up with this message. This is not happening to other files
![image](https://cloud.githubusercontent.com/assets/10192106/7927086/a517b4f8-091e-11e5-9933-0da2386632d6.png)

**Comment by jmervana** [comment]
@mnarewec 
I have tested in your database which you have given yesterday and its working fine for file number 2015-0039

**Comment by mnarewec** [comment]
ok. will close it this time
