### ISSUE TITLE
Bill Generation - Running Draft/Final Bills

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#134]
Right after running a draft bills and if you just select few files from the list of all the files that were selected to run draft biller and run final draft, IT run FINAL Draft for ALL files. this is not right. This issue has been raised before and implemented in v1.7.7 or 8 but it is not implemented.

I have suggested earlier to implement this rule: While on Draft stage, and if there is changes to the selection of the files then 'Hide' the 'Run Final Bills' button and this will force users to run the draft again to the new selection.

**Comment by jmervana** [comment]
@mnarewec 
it is already handled but now I hide the button when changes to selection of file

**Comment by mnarewec** [comment]
This is implemented. Thanks
