### ISSUE TITLE
Changes to Twivey Bill Format

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#135]
(1) In the Bills Printing Defaults, if all or any options under 'Show on Bills' are checked then it should be reflected on Twivey Bills format. For instance, Rate is checked then Lawyer's rate should show on Bills (Draft and Final), and if Professional Time Summary is checked then it should show on Bills (Draft and Final)

(2) Include column headings (Date, Description, Hours, Rate, Value)

(3) Change the Hours (units) format back to like the Bradshaw's format i.e 01 units now becomes 0.1

(4) Re-organise the columns  and or reduce font size so that so all columns can fit nicely.

**Comment by jmervana** [comment]
@mnarewec 
(1) we have no professional time summary in twivey bills format

**Comment by mnarewec** [comment]
No. that's why I want you to show it there too.

**Comment by jmervana** [comment]
@mnarewec 
okay I will show it

**Comment by jmervana** [comment]
@mnarewec 
1st point is already done in CR7

**Comment by mnarewec** [comment]
Professional Time Summary is not showing that's why its listed here.

**Comment by mnarewec** [comment]
@jmervana , Export to PDF button is missing

**Comment by jmervana** [comment]
@mnarewec 
Export to pdf button is in only print all bills and it is there in my side

**Comment by mnarewec** [comment]
Export is working but the ACTUAL requirements are still pending. Please rectify @jmervana

**Comment by jmervana** [comment]
@mnarewec 
What is pending in this task?

**Comment by mnarewec** [comment]
Sorry that's resolved
