### ISSUE TITLE
Tools - Database Backup

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#136]
(1) Provide a option for user to define default backup directory
(2) Give option for user to provide which directory to backup file to (Browse Button) at the time of running back. the Default path should be (1) abouve

**Comment by jmervana** [comment]
@mnarewec 
from where we fetch default path for backup directory.

**Comment by mnarewec** [comment]
@jmervana , there you have it. in the 'System Defaults' page. Create an option for user to define a default directory backup path. Then the backup can fetch it from there.

**Comment by jmervana** [comment]
@mnarewec 
browsing folder on server is not possilble.
what do you suggest for this?
according to me , we can take path as text from user and save that path.

**Comment by mnarewec** [comment]
OK we take path as text from user

**Comment by mnarewec** [comment]
This change as been implemented.
