### ISSUE TITLE
Bill Report (Draft & Final) - Bradshaw Format - Professional Time Summary

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#139]
Lawyer name not showing on Professional Time Summary on 'Draft/Final' Bills Bradshaw Format. On the image, I did not high light it correctly. It should be 'Professional Time Summary'

I am with Client, and they want to send the Bills out now. 

Please assist URGENTLy

![image](https://cloud.githubusercontent.com/assets/10192106/7997927/5adbe7ea-0b78-11e5-985f-89915316a585.png)

**Comment by mnarewec** [comment]
Now it shows the Initials, but want it to show Lawyers Name like before.
![image](https://cloud.githubusercontent.com/assets/10192106/8009103/a330f5be-0be9-11e5-8489-485d667fba8e.png)

**Comment by AAndharia** [comment]
@jmervana  - please advice on this.

**Comment by jmervana** [comment]
@AAndharia 
This is CR.
before CR7, we display lawyer name there but in CR7 requirement is to show initials.

**Comment by mnarewec** [comment]
This has been tested and its confirmed ok.
