### ISSUE TITLE
Reports - Outstanding Bills Details - Revert to previous report

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#140]
This is the image of the Outstanding Bills Details Report. This change was captured in 1.6.4 and later, but it was not implemented in any of the versions of 1.7.

Please implement ASAP !!

![image](https://cloud.githubusercontent.com/assets/10192106/7999184/65b044b0-0b8a-11e5-8b3b-bd35304aba62.png)

**Comment by jmervana** [comment]
@mnarewec 
in document of CR7 , you requested to show client list modal instead of batch list

**Comment by AAndharia** [comment]
@jmervana - please include this in CR sheet.

**Comment by mnarewec** [comment]
This is resolved.
