### ISSUE TITLE
Billing - Bill Generation -- Add/Update Batch

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#141]
(1) Include field File Type  to filter record - it should be type head. All field type should be selected by default.

(2) In lawyers selection filter -  include a default 'All' to select all lawyers. Or that's not possible then all lawyers should be selected by default when creating the batch.

(3) Include File Number to filter records - it should be typed head like select lawyers field. If one or more files are selected from this field, then HIDE the fields 'Minimum WIP Amount', 'File Type', 'Lawyers'. 'All' should be the default value, if that is not possible then leave blank.

(4) the Batch Creation (Update) screen should be ordered like this Period End Date, Description, File Numbers, File Type, Minimum WIP Account, Lawyers, and finally read only Batch date/time

(5) When a Batch is updated after a DRAFT is ran, please remember its selection, i.e., the files that's are selected for draft. This is so that the user do not need to select those files again. Sometimes it is over 100 files and they waste time re-selecting those files again.

**Comment by jmervana** [comment]
@mnarewec 

1. we have two file type , Normal and Fixed Rate. we can use dropdown to select file type why you need typehead there.

2. if there are 100 lawyers and user want to select 2 lawyers at that time he has to remove 98 lawyers from typehead , I think this is not good. 

3. as per my understanding, if file number is selected than remove all filters.

**Comment by mnarewec** [comment]
(1) So that user can select one or both

(2) Please advise if its possible to include a default 'All' - which represent and will select all lawyers at the background when processing filters?

(3) Only the Period End Date and File Number remains, all the other filters can be hidden.

**Comment by jmervana** [comment]
@mnarewec 
for the first point , we can use two checkboxes.

for the 2nd point , we can do that if user will not select any lawyer then we process all lawyer in background. we just give note under typehead that if you not select any lawyer by default it will take all lawyer to process.

**Comment by mnarewec** [comment]
Ok that's fine.

**Comment by AAndharia** [comment]
@jmervana  - is this estimated in CR, if not estimate it. after it assign me. Don't start work yet.

**Comment by jmervana** [comment]
@mnarewec 
for point 5

update batch means criteria for select file will be changed , so drafted files may not be include in that criteria. please suggest.

**Comment by mnarewec** [comment]
Very good point. 

In the case where criteria for select file(s) are changed then,  disregard this requirement (i.e. remember selected files). This only applies when criteria of the file is NOT changed.

**Comment by mnarewec** [comment]
1. Include message on File and Lawyers type head that if no files/lawyers are selected, then all files/lawyers will be selected

**Comment by mnarewec** [comment]
2. When a file is selected, the other filter criterias (File Type, Minimum WIP Amount, and Lawyers) below it are still there. Requirement is for them to be hidden.

**Comment by jmervana** [comment]
point 1 is completed 
point 2 is not reproduced at my end

**Comment by mnarewec** [comment]
This issue has been *implemented*
