### ISSUE TITLE
SETUP - Re-arrangements

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#142]
a.	Rename section ‘System’ to ‘General’
 b.	Create new section called 'Management'
c.     Move  page ‘Disbursement Types & Rates’ to ‘Billing’ section

**Comment by jmervana** [comment]
@mnarewec 

which link should be come under management section?

**Comment by mnarewec** [comment]
@jmervana page defined in #143

**Comment by mnarewec** [comment]
This change as been implemented.
