### ISSUE TITLE
SETUP - Billing - Create a new page 'Billing Defaults'

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#144]
(1) Create a new page ‘Billing Defaults’ and place in the section ‘ Billing’ but in front of ‘Bills Printing Defaults’

(2) ‘Billing Default Page’ divided page into section  section ‘Timesheet Entry’ , 'Disbursement Entry' and Bill Generation

(3) Move the fields: Use Time Code Description, Use Lawyer’s Rate – in Company Information page to this page under  section 'Timesheet Entry'.  Rename ‘Use Time Code Description’ to  ‘Use  Time Codes’

(4) Put this option in ‘Billing Defaults Page’ under time section ' Timesheet entry  :  ‘Include Multiple Lawyers in Timesheet Entry’. Default is NOT checked. If checked then in Timesheet Entry–Add/Modify window, it will show ‘select other lawyers’ field otherwise it will not show.

**Comment by jmervana** [comment]
@mnarewec 

as per my understandin,

no. (2) is to make page with three section
1. Timesheet Entry
2. Disbursement Entry
3. Bill Generation

Timesheet Entry Contains Two options
1. Use Lawyer’s Rate
2. Use Time Codes
3. Include Multiple Lawyers in Timesheet Entry

above three options are false by default
if 3rd is false than user can not add multiple lawyers in timesheet entry else user can


Please correct me if any mistake

**Comment by mnarewec** [comment]
1. Use Lawyers rate should be true by default
2.
3, Yes if false then user cannot add multiple lawyers i,e, hide that field in View by Lawyers entry pop entry up and in view by files pop up entry, best to have a drop down to select a lawyer.

**Comment by jmervana** [comment]
@mnarewec 
view by files have a file owner is default user then why we need to give dropdown there for select lawyer?

**Comment by mnarewec** [comment]
@jmervana, The default owner is NOT always the lawyer who will work on the file so there should be an option to select another lawyer

**Comment by mnarewec** [comment]
(1) Item 'Billing Defaults' should be in front of item 'Bills Printing Defaults'

(2) Option 'include Multiple Lawyers in Timesheet Entry’ is not checked but I can still see lawyers dropbox list in the timesheet add/edit popup window. When it checked ' it will show but when it is unchecked it should not show.

**Comment by mnarewec** [comment]
This issue is still pending @jmervana

**Comment by jmervana** [comment]
@mnarewec 
1st - it will resolved after comments but in new release 
2nd - works fine at my side

**Comment by Talmax** [comment]
Refer attached image.
![image](https://cloud.githubusercontent.com/assets/13091499/8563853/b7743c2c-2587-11e5-944f-48b009788b94.png)

**Comment by jmervana** [comment]
@Talmax 
its a requirement. if you check that checkbox include multiple lawyer then instead of this dropbox , you can see typehead from which you can select multiple lawyers.

**Comment by Talmax** [comment]
This issue has been confirmed solved.

![image](https://cloud.githubusercontent.com/assets/13091499/8665676/ec3a8096-2a29-11e5-83c3-42ffbb533efc.png)

**Comment by mnarewec** [comment]
@jmervana, this issue is still not resolved. When you unchecked the 'Include Multiple Lawyers in timesheet entry' as shown below.

![image](https://cloud.githubusercontent.com/assets/10192106/8764107/9973d55e-2e04-11e5-8a59-8490fe0f35b6.png)

the lawyers drop down list in Add/Edit pop up window of Timesheet Entries >>View by Lawyers SHOULD NOT SHOW

![image](https://cloud.githubusercontent.com/assets/10192106/8764112/fbf2c186-2e04-11e5-94ce-7bcfd2539461.png)

**Comment by jmervana** [comment]
@mnarewec 
that prevent user to select multiple lawyers
in above screenshot , you can see there is no option for user to select multiple users.
if you checked checkbox user can select multiple user , it is also mentioned in above comments too.

**Comment by mnarewec** [comment]
Our requirement is NOT to show because the user already select the Lawyer.

**Comment by jmervana** [comment]
@mnarewec  just see screenshot below that screenshot is from this task

![image](https://cloud.githubusercontent.com/assets/7436116/8775192/77f13084-2f03-11e5-9ea4-f7b4aae6cecc.png)

**Comment by mnarewec** [comment]
The requirement is clearly there: "Hide that field in view by lawers"

**Comment by mnarewec** [comment]
I said 'HIDE' not ' READ ONLY;..anyway, will accept this change because we are going around circle

**Comment by AAndharia** [comment]
@jmervana - please discuss this with me.
