### ISSUE TITLE
SETUP - Billing - Bills Printing Defaults

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#145]
(1) In the page ‘Bills Printing Defaults’ under section ‘Select Option to show in Bills’ align the options vertically.

(2)i.	Move the field ‘Show Printing Defaults’ to ‘Bills Printing Defaults page’ from ‘System Default Page’

**Comment by jmervana** [comment]
@mnarewec 

what should be come in system default page? because right now there are two options which will move to other page in this CR1.8

**Comment by mnarewec** [comment]
Hide it in the meantime until we see a need in the future.

**Comment by mnarewec** [comment]
@jmervana , refer #136 , you will create a field to store database backup default path.

**Comment by mnarewec** [comment]
This change has been implemented.
