### ISSUE TITLE
Bill Generation - Export to PDF - Draft Bills

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#148]
I recall I approve CR to rename the PDF file name. It was implemented in CR 1.6 releases but not this time. Please correct this mistake.
![image](https://cloud.githubusercontent.com/assets/10192106/8009352/a2643180-0beb-11e5-9823-865e94a629dd.png)

**Comment by jmervana** [comment]
@mnarewec 
I got the filename viewproof when I save file.

**Comment by mnarewec** [comment]
It should be viewproof... it should be 'Draft Bill (period end date).pdf
just like how the Final Bills is named.

**Comment by AAndharia** [comment]
@jmervana - is this new CR or missed requirement?

**Comment by jmervana** [comment]
@AAndharia 
it is implemented in view final bill and this was implemented in 3rd or 4th CR.

**Comment by mnarewec** [comment]
It is in Final Bill but I want it in Draft Bills too @jmervana

**Comment by AAndharia** [comment]
@jmervana  - please do this, considering a small enhancement.

**Comment by jmervana** [comment]
@AAndharia 
ok I will do it

**Comment by jmervana** [comment]
@mnarewec 
this will be resolved in next release

**Comment by mnarewec** [comment]
This has been resolved.
