### ISSUE TITLE
Bill Generation - Batch List View

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#149]
(1) Batch list view - Do not show empty batch (i.e. all bills deleted) on the Batch List view. This new rule should be added to the current rule where Batch which have all its bills whose outstanding amounts are zero should not be displayed.

(2) Batch list view - should have have a drop down list to filter Draft and Final Batch. Default should be 'All Batch'.

**Comment by AAndharia** [comment]
@jmervana - please estimate and include in sheet and assign back to me.

**Comment by mnarewec** [comment]
This change is implemented. THank you
