### ISSUE TITLE
Bill Generation - Final and Draft Bill Views

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#150]
(1) Include another field to show Outstanding Amount
![image](https://cloud.githubusercontent.com/assets/10192106/8276656/5d841742-18fc-11e5-92a9-d9a70b4f9aed.png)

(2) The Bill Cannot be deleted if the Outstanding Amount is Not Equal to Total Amount . That is, partial payment has already been received for that Bill.

(3) The Transaction list should NOT show Bills, whose outstanding amount is Zero. That is, bills fully paid should not be on the transaction list.

**Comment by AAndharia** [comment]
@jmervana - please estimate and add time in estimation sheet. Assign me back once done.

**Comment by mnarewec** [comment]
This issue has been tested and confirmed ok.
