### ISSUE TITLE
Change all Kumulsoft Billing System label

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#152]
Change all Labels including on the Reports including those exported to PDFs from 'Kumulsoft Billing System' or 'Kumulsoft Billing Solution' to just 'Kumulsoft Billing'

**Comment by AAndharia** [comment]
@jmervana - please estimate and add time in estimation sheet. Assign me back once done.

**Comment by Talmax** [comment]
This change has been implemented
