### ISSUE TITLE
Billing Generation - Billing Batch- Update Batch button is not shown when batch is filtered by Draft Bills

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#155]

**Comment by jmervana** [comment]
Discussed with @mnarewec 
This is not bug but he need to show new batch in draft batch filter

**Comment by AAndharia** [comment]
Please implement this considering small enhancement and include in next release.

**Comment by jmervana** [comment]
@mnarewec 
as we discuss there is no problem with update button and add new batch to draft batch filter. I will do that in next release

**Comment by Talmax** [comment]
This issue has been confirmed resolved.
