### ISSUE TITLE
Bill Generation - Final /Draft Bills -- Export to PDF unresponsive

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#156]
It takes 'forever' to export. Twice it resulted it 'Chrome prompt to kill process or wait'.

![image](https://cloud.githubusercontent.com/assets/10192106/8516631/0b71ddaa-23fa-11e5-9d40-3099eb9f8976.png)

Please check and rectify

**Comment by jmervana** [comment]
@mnarewec 
Would you please show me and I want to know that how many files selected to export?

**Comment by Talmax** [comment]
This issue has been confirmed solved

**Comment by mnarewec** [comment]
@jmervana , cc @AAndharia This is a serious issue and needs to be resolved before end of the month Billing. I m able to Export to PDF more less than 15 Bills More than that result in 'Unresponsive Page' error. This is very critical issue because usually print more than 60 or 70 bills or even 100 in a month. 

Please treat this issue with utmost URGENCY and release in 1.8.5 since we are nearing the end of month year and this will be the time to run bills.

here is the link to the database if you want to reproduce:
https://drive.google.com/a/kumulsoft.com/file/d/0B9T2hcAcxJgLWkxJajRtTG5DeUU/view?usp=sharing

**Comment by AAndharia** [comment]
@jmervana - work on this with highest priority.

**Comment by AAndharia** [comment]
@mnarewec  - as per our chat discussion today, this is what we are going to implement now.

1. We'll not show any data on the browser page
2. User just select the files and hit submit and it would generate the pdf 
3. while generating pdf may take minutes (a lot time depending on number of files selected), but we'll always show the indicator to user that something is going on and user will not be able to do any action during that time period and also browser will not crash.

**Comment by mnarewec** [comment]
@jmervana , this issue is resolved. Now the export of 68 bills is less than a minute (30 sec). There is one issue though, I configure to show the Bills Printing Default page, who when exporting it shows me the Billing Printing Defaults page, but the selection I made on this pop up window is not working. For example, it was default to Bradshaw format, and show Initials, Rate and Value so on the Bills Printing default window I select Twivey format and unselect Intials, Rate and Value but it still show Bradshaw's format

![image](https://cloud.githubusercontent.com/assets/10192106/8984383/90341508-3714-11e5-8bb2-b955a9806ec0.png)

![image](https://cloud.githubusercontent.com/assets/10192106/8984394/a9a4a818-3714-11e5-995e-85eb5225e444.png)

**Comment by mnarewec** [comment]
This has resolved. THanks
