### ISSUE TITLE
1.	Bill generation – Final/Draft bills not paging correctly. Every bill should start as a new page

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#158]
![image](https://cloud.githubusercontent.com/assets/13091499/8539742/6dd4bbfc-24c2-11e5-8e24-3b7f11797a19.png)

**Comment by jmervana** [comment]
@mnarewec @Talmax 
this works fine at my side.
would you please double check with this? and make sure you are testing on correct version.

**Comment by Talmax** [comment]
@jmervana we double check and the issue still persist. Maybe this is due to the fact that we cannot upload the logo that may generates that page break.

**Comment by AAndharia** [comment]
@mnarewec - can you please check in your version and confirm this is not working?

**Comment by mnarewec** [comment]
@AAndharia , its working at my no problem. The only difference is Talmax  has no logo (is unable to upload a logo - same issue with me) and I have logo (existing company logo).

**Comment by AAndharia** [comment]
@jmervana - I believe its problem with the version, but still please investigate once again.

**Comment by Talmax** [comment]
This issue has been confirm solved
