### ISSUE TITLE
Setup – company information – unable to upload and update company logo.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#159]
![image](https://cloud.githubusercontent.com/assets/13091499/8539780/befa3e26-24c2-11e5-9b7f-b3082e0f6028.png)

**Comment by AAndharia** [comment]
@mnarewec - please verify permission to the folder. It is working at our end.

**Comment by Talmax** [comment]
@jmervana ,cc @AAndharia IIS Users/users have full permissions to the kumulsoft folder.

**Comment by AAndharia** [comment]
@mnarewec - please help Talmax with this. This is issue with setup not development.

**Comment by mnarewec** [comment]
@AAndharia I am also have the same issue. We are unable to change logo. We have full permissions to the web application folder.

**Comment by jmervana** [comment]
@mnarewec 
sorry for that, this will be resolved in next release

**Comment by Talmax** [comment]
This issue has been confirm solve

**Comment by mnarewec** [comment]
confirmed
