### ISSUE TITLE
Bill generation – outstanding bills permission not working.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#160]
Bill generation – outstanding bills. The permission for outstanding bills did not work because the logic interprets the menu name as out standing and not as outstanding. Please rectify this.

**Comment by jmervana** [comment]
@Talmax 
This works fine at my side.
if you want to see , I will see you but I want to show at your side.

**Comment by Talmax** [comment]
Regard this issue has closed because we will going forward change the db permission name for outstanding bills to 'out standing bills'
