### ISSUE TITLE
Banking>>Receipt Bills. Create New Receipt Report Format

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#161]
(1) The format/layout of the receipt is shown below in the image

Receipt Format
![image](https://cloud.githubusercontent.com/assets/10192106/8817811/a95f40b0-307b-11e5-9a15-7bfd91b881df.png)

**Comment by AAndharia** [comment]
@mnarewec - please provide us a sample format for the receipt & more details about what information you need to include in it.

**Comment by AAndharia** [comment]
@mnarewec - feq questions 

1. Logo and Company details will be LawFirm Details, am i right?
2. Where should we give option to Email or Print? I think Receipt Transaction Tab Grid, am i right?
3. Right after receipt is generated, should we proceed "Email" function? Or user will click the email or print button manually?
4. Is there any specific preference for the font family and font size for this report?
5. Are you sure we have to open default email program? Setting attachment to default email program will not be possible unless we know what program it is, and that we'll have to pre-decide before programming. Also, once we decide that, we'll have to use some dlls from microsoft (which may need some licensing) to accomplish this task. I think it would be better that email is sent from KSB system itself. We'll prefill the information you mentioned, show a popup, user will enter the body and email will be sent to the user - for this you'll need an SMTP Email Server & a common email address will be used as "From Email". Please suggest.
6. What if there is no default email program installed on user's machine?
7. I think subject line for the email should be more relevant so that user can know even before opening an email that this is from KSB and for what purpose.
8. In subject line, what is : XXXXXX ? what field is it?
9. In subject line [Company Name] means law firm name?
10. what should be the name of pdf for download?
11. what should be the name of pdf for attachment?

**Comment by AAndharia** [comment]
Please analyze and estimate

**Comment by jmervana** [comment]
@mnarewec 

Should I add new field to database for Receipt Number?
Click on print , submit data and export it to pdf and download, am i right?

**Comment by mnarewec** [comment]
There is no need. Just format the transaction id as per requirement

**Comment by jmervana** [comment]
@mnarewec 
Click on print , submit data and export it to pdf and download, am i right?

**Comment by mnarewec** [comment]
Yes right

**Comment by mnarewec** [comment]
1. Make changes as per image below
![image](https://cloud.githubusercontent.com/assets/10192106/9353628/1bda8e3c-46ad-11e5-9d7a-55bb4a898588.png)

**Comment by mnarewec** [comment]
This is resolved.
