### ISSUE TITLE
Reports >> Client Management. Create new Report 'Trust Account Statement'

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#162]
1. This report can be exported to PDF and format it in Portrait

2. Data Filtration options, 
 (1) Date Range (From Date and To Date)
 (2) One file or multiple files
 (3) One Client or Multiple Client
 (3) Transaction Type (Deposit, or Withdraw (pay bills) or Both)

Report Layout should be  formatted similar to Statement of Account Report

(1) HEADER should be like this
![image](https://cloud.githubusercontent.com/assets/10192106/8796851/520e3762-2fdb-11e5-9218-ffdee3718771.png)

(2) BODY
It should have following columns : Transaction Date, Transaction Type, File Number, Subject Matter, Transaction Amount, Balance 

**Please note: If transaction type is Deposit (DEP) then Amount is added to Balance,  if transaction type is Payment(PAY) then amount is reduce from the balance
** Sorted by Date
** Show Final Balance after all transaction
  
(3) FOOTER
Insert 'Kumulsoft Billing' and Page Number

**Comment by AAndharia** [comment]
@mnarewec - please provide report format and information to be included in the report and more details about from which form and based on what criteria you need this report to be generated.

**Comment by mnarewec** [comment]
1. This report can be exported to PDF and format it in Portrait

2. Data Filtration options, 
 (1) Date Range (From Date and To Date)
 (2) One file or multiple files
 (3) Transaction Type (Deposit, or Withdraw (pay bills) or Both)

**Comment by mnarewec** [comment]
@AAndharia , change Milestone to CR 1.8 - Tidy up

**Comment by AAndharia** [comment]
@jmervana  - please analyze and estimate. Ask any questions you may have.

**Comment by jmervana** [comment]
@mnarewec 

so its like client statement report

for one file one report will be generated with all its transaction.
Show Final Balance after all transaction - as per my understanding this is balance column in each row with remaining balance at the time of specific transaction.

**Comment by AAndharia** [comment]
1. Do we have to only show transactions used to Pay Bills... in earlier database, there will be records which may be used to Pay for Disbursements.
2. A4 size compatible
3. Do you prefer any font family or size?
4. I think we should show Trust Fund name somewhere on report
5. If we chose multiple file, new file will start on new page in PDF
6. What should be the name of pdf?
7. from where this report should be opened?

**Comment by AAndharia** [comment]
@jmervana - please analyze and estimate.

**Comment by jmervana** [comment]
@mnarewec 

What about permission for this report?

**Comment by mnarewec** [comment]
Yes set permissions for this report

**Comment by mnarewec** [comment]
This is very good. Few Changes

1. Change label as per image below
![image](https://cloud.githubusercontent.com/assets/10192106/9354433/b66b42d8-46b3-11e5-8b86-954954015a4a.png)

2. Force Page break when change of client, i.e. exactly like Statement of Account., so it prints new header, when the client name changes.

**Comment by jmervana** [comment]
@AAndharia 

This is CR.
This requirement is time taking as we used iTextsharp

**Comment by AAndharia** [comment]
@mnarewec - please convert this to new issue and make it CR need estimation. If you need discussion about why is it CR. please ping me on GTalk.

**Comment by AAndharia** [comment]
@mnarewec - i've created new issue to maintain changes. it is : #199 . You can close this issue if everything else is fine.
