### ISSUE TITLE
Proposed Features by Team Ingenious 

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#165]

**Comment by mnarewec** [comment]
@AAndharia, List above in numerical order your propose changes.

**Comment by AAndharia** [comment]
Done. Please check : https://docs.google.com/document/d/19U3QYYJaXxbW3pEii8E8phj-iczH9C85i6SQF3Ybyj8/edit?usp=sharing

**Comment by mnarewec** [comment]
No need...will discuss later
