### ISSUE TITLE
Outstanding bills bar graph is not showing when not connected to the internet

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#166]
This is the error message it gives

![image](https://cloud.githubusercontent.com/assets/13091499/8760168/f97f3e0c-2d50-11e5-93a0-b20cb16921b9.png)

**Comment by jmervana** [comment]
@Talmax 
we are using google charts here so if you have not internet connection then it throws an error , we handle that error and shows this message

**Comment by mnarewec** [comment]
@jmervana most if not all our users do not have internet connection. Please resolve this issue. Our requirement is show the grap to the users irrespective of internet connection.

**Comment by AAndharia** [comment]
@mnarewec - this can't be done If we use google charts. Please suggest if we should not use google chart, which tool is required to be used. We used google charts as per initial requirements. I do not recall we ever discuss that internet will not be available.

**Comment by mnarewec** [comment]
You are the developer and supposed to give a graph as per my requirement.

**Comment by AAndharia** [comment]
@mnarewec, when graph was built earlier we were building the application as SAAS and this was given the best possible free option considering the fact SAAS can't be used without internet. Also I remember for every third party tool we use, we ask you for confirmation before using it.

**Comment by Talmax** [comment]
This issue has been solved.
