### ISSUE TITLE
Bill Generation - bills(PDF) page numbering not correct.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#167]
Refer attached.

![image](https://cloud.githubusercontent.com/assets/13091499/8760298/cbc648f6-2d56-11e5-85eb-13291f04e691.png)

**Comment by jmervana** [comment]
@mnarewec , @Talmax 
This is resolved

**Comment by Talmax** [comment]
When export or to print the final/draft bill,the logo is not showing. refer the image below.

![image](https://cloud.githubusercontent.com/assets/13091499/8794496/96e2ca1a-2fc7-11e5-9a11-657c80e76736.png)

**Comment by Talmax** [comment]
This issue has been confirmed solved.

![image](https://cloud.githubusercontent.com/assets/13091499/8794684/28f5b48e-2fc9-11e5-8931-30936dcf7c50.png)
