### ISSUE TITLE
Batch Update Issue - Unable to do 2nd update of the screen

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#168]
I just create update a batch with a single file selection, and then did update same by removing the Single file and update the minimum amount. The batch only generate for that single file and not multiple files as I expected. When I want to do update again, it does not allow me.

![image](https://cloud.githubusercontent.com/assets/10192106/8764145/4fa0efa4-2e07-11e5-81c1-569514f35918.png)

**Comment by mnarewec** [comment]
@jmervana , also try test deleting that batch, it will come up with a run time error

**Comment by jmervana** [comment]
@mnarewec 
This is resolved

**Comment by Talmax** [comment]
This issue has been confirmed resolved.
