### ISSUE TITLE
Statement of Account Font Size is not professional.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#170]
Please use the previous font size.Refer to the export PDF/Print view of a client statement, see image below.

![image](https://cloud.githubusercontent.com/assets/13091499/8796558/edace39c-2fd8-11e5-814d-168af923e660.png)

**Comment by AAndharia** [comment]
@Talmax  - please provide exact font size & font family to be used and we'll do this. At present what we have has already been confirmed with Marsh earlier.

**Comment by mnarewec** [comment]
@AAndharia , I can't recall asking you to change font size and style but Please font style as defaulted in Bills Printing Defaults.

**Comment by AAndharia** [comment]
@mnarewec - is there any other place where you need to do the same change?

**Comment by mnarewec** [comment]
Correct this Statement Report

**Comment by AAndharia** [comment]
@jmervana - please change this fonts as per standard fonts used everywhere.

**Comment by AAndharia** [comment]
@mnarewec  - this will be part of CR. You may decide if it has to be done or not.

**Comment by mnarewec** [comment]
1. *Refer comments on image below
![image](https://cloud.githubusercontent.com/assets/10192106/9352100/e89b8946-46a1-11e5-8e29-ff928591716b.png)

**Comment by jmervana** [comment]
@mnarewec 

this is not technically supported by iTextsharp.

**Comment by AAndharia** [comment]
@mnarewec  - What Japan means is aligning subject matter to middle is not technically possible with iTextSharp. Page break can be done.

**Comment by mnarewec** [comment]
1. But you were able to achieve it with Draft and Final Bills. Refer image below
![image](https://cloud.githubusercontent.com/assets/10192106/9397158/53a4ade4-47dd-11e5-830c-ae7a520d08b9.png)

2. Remove the extra last blank page.

**Comment by AAndharia** [comment]
@jmervana - your thoughts on this?

**Comment by mnarewec** [comment]
This is resolved.

**Comment by mnarewec** [comment]
This is accomplished.
