### ISSUE TITLE
Managment >> Trust Fund >>Change to Trust Fund Business Rule

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#171]
Trust funds should ONLY be used to pay bills. Any Disbursements must be converted to Bills first before before using trust funds to pay bills.

(1) Therefore remove the functionality to use trust funds to pay disbursements in Manage Trust Funds.

**Comment by AAndharia** [comment]
@jmervana - please analyze and provide estimation

**Comment by jmervana** [comment]
@mnarewec 

so there should be only two tabs, Transaction & PayBills, Pay disbursement should be remove with all its functionality from this page.

**Comment by AAndharia** [comment]
@mnarewec - few more questions in addition to what Japan asked above 

1. Do we have to handle any existing data or make any database changes, or leave them as it is?
2. I think it would be good if we just show those file names which has at least one outstanding bill to the left now - is that good idea?

**Comment by AAndharia** [comment]
Feedback on my questions ?

**Comment by AAndharia** [comment]
@Japan - please analyze & estimate.

**Comment by mnarewec** [comment]
Thanks. Resolved.
