### ISSUE TITLE
Twivey Bills (Draft/Final) Format Issues

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#172]
In Bills Printing Defaults, Professional time and Total are checked.
![image](https://cloud.githubusercontent.com/assets/10192106/8797717/ab3e2298-2fe0-11e5-849d-b796b17c6738.png)

But they are not showing on Twivey Format. Refer two images below

![finalbills 22-05-2015 1 _001](https://cloud.githubusercontent.com/assets/10192106/8797758/eacadbb8-2fe0-11e5-86ba-4d994e3c16e3.png)
![finalbills 22-05-2015 1 _002](https://cloud.githubusercontent.com/assets/10192106/8797762/eea6172a-2fe0-11e5-86e7-f2ed0c4d61c4.png)

**Comment by jmervana** [comment]
@mnarewec 

This is resolved

**Comment by mnarewec** [comment]
yes
