### ISSUE TITLE
Bradshaw Bills (Draft/Final) format issues

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#173]
When Total is unchecked in Bradshaw Format, it is still showing in the Bills. Which shouldn't be the case
![image](https://cloud.githubusercontent.com/assets/10192106/8797966/67671b2c-2fe2-11e5-9aa1-0706474c938b.png)

it should not show but its showing.
![image](https://cloud.githubusercontent.com/assets/10192106/8797994/9a7c14cc-2fe2-11e5-8d56-0bec1744bd4b.png)

**Comment by jmervana** [comment]
@mnarewec 

This total is not for value column it is for Timesheet Entries Totals

**Comment by AAndharia** [comment]
@jmervana - please analyze & estimate. Let's discuss after it.

**Comment by AAndharia** [comment]
We'll not consider this as CR.

**Comment by jmervana** [comment]
@mnarewec 
This is resolved

**Comment by mnarewec** [comment]
Yes
