### ISSUE TITLE
Billing >> Outstanding Bills

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#174]
Create an option in this view/feature for user to be able to export a bill. 

(1) Create a extra column called Action, and list down print icon on all bills so when user click it will link them to display the final bill and and enable option to print.

(2) This also solves resolves the 'Single Bill' Print of Bill Generation >> Final Bills.

[Japan : 24Jul] [print means print or export to pdf]

**Comment by AAndharia** [comment]
@jmervana - please analyze & estimate.

**Comment by jmervana** [comment]
@mnarewec 

as per my understanding,

last column of grid have button named export, when user clicks on it we have to export that bill as pdf report, isn't it?

what do you want to include in this report? I mean which information about specific bill.

**Comment by AAndharia** [comment]
1. Is that any existing report, that we have to generate here as PDF? I think it should be Outstanding Detail report for this specific bill. or is it something else? If so, please provide a sample format for this new report.
2. what should be the name of PDF?

**Comment by AAndharia** [comment]
@jmervana - please analyze and estimate

**Comment by AAndharia** [comment]
@mnarewec 
Here we have considered that when user click to export the pdf, it would behave same as generating Final Bill Report from Bill Generation module. Meaning, it would open popup to select format if relevant settings is set, otherwise it would generate the report directly with default format. - Please confirm.

**Comment by jmervana** [comment]
@mnarewec 

I have added one quetion with label [Japan : 24Jul] in wiki.

**Comment by mnarewec** [comment]
It will be like implementing Print Selected Bill in Bill Generation>>Final
Batch>>Final Bill. But this time it will have an PDF export button.

**Comment by mnarewec** [comment]
OK but only the PDF File Name is incorrect

**Comment by jmervana** [comment]
@mnarewec 

I have checked it it is ok.

![image](https://cloud.githubusercontent.com/assets/7436116/9376789/48bb1a8e-472f-11e5-941a-045da48b949e.png)

**Comment by mnarewec** [comment]
@jmervana ?????

**Comment by jmervana** [comment]
@mnarewec 

I have checked pdf file name is correct

**Comment by mnarewec** [comment]
@jmervana our requirement for Outstanding Bills should be :

 Marsh: 'Bill -NNNN.PDF', where NNNN=Bill Number

**Comment by mnarewec** [comment]
This has been resolved.
