### ISSUE TITLE
Bill Generation - Changes to Twivey Final Bill Format

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#175]
Sometimes a Bill is partial paid using Trust Funds or thru Receipts. We need to show that payment on the Bill.

(1) Bradshaw Format.
      (a) Create a section called 'Payments Received' just below Amount Payable. 
      (b) List and identify clearly whether payment received from Trust Fund or Receipts. 
      (c) Show payments received total. 
      (d) "Our Charges" should be the outstanding amount. 
      (d) AND DO NOT SHOW THIS SECTION IF THERE IS NO PARTIAL PAYMENTS OR NO Payments from Trust Fund.
   (e) IF BILL IS FULLY PAID, IT SHOULD STILL SHOW BUT THE 'Our Charges'  will be zero i.e. 0.00

![image](https://cloud.githubusercontent.com/assets/10192106/8798863/e14d1e9a-2fe8-11e5-8f4a-c47fa85d8389.png)

(2) Twivey Format
      (a) Create a section called 'Payments Received' just below Disbursements section 
      (b) List and identify clearly whether payment received from Trust Fund or Receipts. 
      (c) Show payments received total. 
      (d) "Total Fees Payable on this Bill" should be the outstanding amount. 
      (d) AND DO NOT SHOW THIS SECTION IF THERE IS NO PARTIAL PAYMENTS OR NO Payments from Trust Fund.
   (e) IF BILL IS FULLY PAID, IT SHOULD STILL SHOW BUT THE 'Total Fees Payable on this Bill' will be zero i.e. 0.00
![image](https://cloud.githubusercontent.com/assets/10192106/8798977/d9fee87a-2fe9-11e5-9e5c-cdc414068413.png)

@mnarewec - few questions

1. in the new section we'll show following information. Transaction Date, Transaction Type (Receipt or Trust Fund) & Amount Received. - Please confirm. 

Marsh: It should be something like that. Refer image below. Note the format of currency.

![image](https://cloud.githubusercontent.com/assets/10192106/8840263/19d7b59c-3122-11e5-84bf-8bd6e378b119.png)

Amit : So it just shows the sum of payment received as Trust Fund & Receipts - no specific details for each transaction with date. I think it would be nice to show all the transactions. Still i'll wait for what you finalize.
Marsh: No details, only summary of Payments Receipt or from Trust Fund payment
Amit : Ok, so we'll just show it same as you've shown here in screenshot, please confirm.
Amit : Marsh, confirmed for this on chat.

**Comment by AAndharia** [comment]
@jmervana - please analyze and estimate. Let's discuss after it.

**Comment by AAndharia** [comment]
@mnarewec - few questions 
1. in the new section we'll show following information. Transaction Date, Transaction Type (Receipt or Trust Fund) & Amount Received. - Please confirm.

**Comment by mnarewec** [comment]
@AAndharia, cc @jmervana Made small changes to the above. Please refer

**Comment by AAndharia** [comment]
@mnarewec - can you please add another comment here for just changes, its not 100% clear what are the changes.

**Comment by AAndharia** [comment]
I think it would always be nice to initially use numbers and for any new comments refer numbers

**Comment by AAndharia** [comment]
or we can use GitHub wiki for specifications, as it would give us clearly differences between past & new comments ... by just highlighting them. Do you think its good idea?

**Comment by AAndharia** [comment]
Copied this to Wiki : 

Page : https://github.com/AAndharia/PSB/wiki/Changes-to-Both-(Twivey-&-Bradshaw)-format-of-Bills-show-payments-made-so-far
History Of Edits : https://github.com/AAndharia/PSB/wiki/Changes-to-Both-(Twivey-&-Bradshaw)-format-of-Bills-show-payments-made-so-far/_history

This way we can easily keep track of any modifications in specifications and keep commenting it and can have one final version of specifications. We still create one issue in issue tracker and just put link to wiki in its description to keep track of status (Ready For Testing, Need Estimation, Ready For Review) etc.

Let me know what you think.

**Comment by mnarewec** [comment]
1. **Refer the following changes **
![image](https://cloud.githubusercontent.com/assets/10192106/9350996/ddcdca50-4698-11e5-84e5-c8147a365c7c.png)

**Comment by mnarewec** [comment]
This is not fixed as per requirement above

**Comment by AAndharia** [comment]
@mnarewec - can u please elaborate what is not fixed?

**Comment by mnarewec** [comment]
This has been resolved together with Bradshaw format.
