### ISSUE TITLE
Management >> Client >> Contact name should not be mandatory

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#176]
We realize that contact name is mandatory, which never be the case. Because sometimes client name is the same as the contact person. The requirement is there in the former BMS. 
![image](https://cloud.githubusercontent.com/assets/13091499/8815317/a887d6be-305a-11e5-9981-8d5b32df1790.png)

**Comment by jmervana** [comment]
@Talmax 

Database given by Marsh should have contact name required in table

**Comment by AAndharia** [comment]
@mnarewec - please advice if we should include this in current CR?

**Comment by AAndharia** [comment]
@jmervana - please analyze and estimate. Make sure it is taken care at all the place ... where it is displayed and where it is edited/added etc.

**Comment by mnarewec** [comment]
This has been implemented. Thank you.
