### ISSUE TITLE
Billing >>Bill Generation. Changes to Bradshaw Final Bill Format

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#178]
Sometimes a Bill is partial paid using Trust Funds or thru Receipts. We need to show that payment on the Bill.

(1) Bradshaw Format.
      (a) Create a section called 'Payments Received' just below Amount Payable. 
      (b) List and identify clearly whether payment received from Trust Fund or Receipts. 
      (c) Show payments received total. 
      (d) "Our Charges" should be the outstanding amount. 
      (d) AND DO NOT SHOW THIS SECTION IF THERE IS NO PARTIAL PAYMENTS OR NO Payments from Trust Fund.
   (e) IF BILL IS FULLY PAID, IT SHOULD STILL SHOW BUT THE 'Our Charges'  will be zero i.e. 0.00

![image](https://cloud.githubusercontent.com/assets/10192106/8798863/e14d1e9a-2fe8-11e5-8f4a-c47fa85d8389.png)

**Comment by mnarewec** [comment]
(1) Header is out of place
![image](https://cloud.githubusercontent.com/assets/10192106/9327394/d8bf77a8-45e3-11e5-82e6-913023748775.png)

(2) Footer is not properly define and formatted.
![image](https://cloud.githubusercontent.com/assets/10192106/9327461/50fb787a-45e4-11e5-95e3-ac1ceeb8aa43.png)

**Comment by jmervana** [comment]
@mnarewec 

payment received is summerised means all receipt in one record and all trust fund in one record.
there are only two rows for this section and third will be total

**Comment by mnarewec** [comment]
@jmervana Yes Japan, and the section should be labeled **Payment(s) Received**

**Comment by mnarewec** [comment]
This is not resolved.

**Comment by mnarewec** [comment]
@jmervana , Please resolve this ASAP. I am at client site and we expect to deliver this TODAY !!!!
![image](https://cloud.githubusercontent.com/assets/10192106/9649259/c40bcdd0-5235-11e5-9aa8-f47929419d9b.png)

**Comment by mnarewec** [comment]
@jmervana , cc @AAndharia  again this one two is not implemented. We specifically asked to revert to previous format

![image](https://cloud.githubusercontent.com/assets/10192106/9649494/1a08b416-5239-11e5-8fa2-fd629380488b.png)

**Comment by mnarewec** [comment]
There are other issues but will raised in new issue, the core of the issue as been addressed.
