### ISSUE TITLE
Banking >> Receipt Bill. Changes to the Receipt Bills 'Receipt Transactions' view

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#179]
(a) Receipt Number as new field. It is text formatted transaction id - Receipt Number be six digits. NNNNNN.  e.g. if transaction id =1, then the Receipt Number is 000001, if transaction id=12, then receipt Number is 000012, if transaction Id= 212 then Receipt Number is 0000212, if Transaction Id =2444, the receipt Number is 002444

(b) Print ICON option, - name the column as Action, and display a print icon on all transactions.
(c) one small additional requirement  - rename 'Add Receipt' tab to 'Outstanding Bills' tab 
![image](https://cloud.githubusercontent.com/assets/10192106/8820096/d125d2de-3095-11e5-960e-ab25a10f283f.png)

**Comment by mnarewec** [comment]
1. Please format rename tab to 'Outstanding Bills' and format receipt reference column as per image
![image](https://cloud.githubusercontent.com/assets/10192106/9354018/3b1eeace-46b0-11e5-953a-b5f2c473697c.png)

**Comment by mnarewec** [comment]
The tab is renamed but the receipt reference is not formatted.

**Comment by AAndharia** [comment]
Formatting would only be done on new data. Please make sure you are testing with newly entered data.

**Comment by mnarewec** [comment]
Ok this issue formatted. Thank you.
