### ISSUE TITLE
Management >> Trust Fund. Changes to 'Add Deposit' popup window

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#182]
Part A - Spelling Changes

1. Rename all labels from 'Trust Fund' to 'Trust Account'
1. Rename label 'Deposite' to 'Deposit'

Part B - Change to the Database
Modify trust account table add new field ; Receipt Type, 

Part C - Deposit Fund pop up window
Make changes as per image below
![image](https://cloud.githubusercontent.com/assets/10192106/8868112/f7a962d6-3216-11e5-94d6-a07eaef82a34.png)

 * (a) Receipt Type is a drop down list with following Values (Cheque, Direct Deposits, Cash)
 * (b) When print button is clicked, it will submit data to database and also print 'Trust Account Deposit Receipt' report (refer #183)

[Japan : 24JUL]

 1. Is Receipt Type is required field?
 1. What will be value for this field in existing data?

**Comment by jmervana** [comment]
@mnarewec 

I have added quetion in wiki with label [Japan : 24Jul].

**Comment by mnarewec** [comment]
Please put questions here.

**Comment by AAndharia** [comment]
@mnarewec - it would be nice if we keep this clean and use wiki only to have the history and avoid any confusion in future.

**Comment by mnarewec** [comment]
Ok. I will try to update

**Comment by AAndharia** [comment]
@mnarewec - please keep using issue tracker. I've moved it all back to Issues.. from Wiki. Looks like its not comfortable to you.

**Comment by AAndharia** [comment]
Please respond on comments from japan with [Japan 24Jul]

**Comment by jmervana** [comment]
@mnarewec 
Please respond on my comments with [Japan 24Jul]

**Comment by mnarewec** [comment]
Is Receipt Type is required field? NOT AT DB LEVEL, BUT YES AT UI LEVEL
What will be value for this field in existing data? NULL

**Comment by mnarewec** [comment]
This is resolved. Thanks
