### ISSUE TITLE
Reports >> File >> File Ledger to Properly Formatted and Export to PDF

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#184]
Format the File Ledger so that it can appear presentable on the Screen and also create option for it to be exported to PDF. It must be formatted in Portrait

**Comment by AAndharia** [comment]
as per our discussion on chat today 

1. we just have to remove Print option and create new one for Export To PDF. 
1. font should come from Bills Printing Defaults. 
1. Format it like what we did for account statement.

**Comment by jmervana** [comment]
@mnarewec 

Would you please tell me the format for this report ? we cannot format it as client statement or client ledger because this report has 6 different tables wherever client statement and client ledger report has a single table per report.

Please suggest

**Comment by mnarewec** [comment]
As advised via Google Talk.

**Comment by mnarewec** [comment]
1. New File or Next file number should force a page break, and the new page should print header (logo etc)

2. Include the text 'File Ledger' with File Number, refer image below
![image](https://cloud.githubusercontent.com/assets/10192106/9352594/d072c6f0-46a5-11e5-8e72-c9c62f8b6ff0.png)

3. Format the hours correctly, see image below
![image](https://cloud.githubusercontent.com/assets/10192106/9352622/0f99dd32-46a6-11e5-9e52-3769c412b532.png)

**Comment by jmervana** [comment]
@AAndharia 

This is CR. we have already small enhancements but this is time taking requirement.

**Comment by AAndharia** [comment]
@mnarewec - please create a new GitHub issue with CR Need Estimation and assign me back. If you feel this is not a CR, please ping me on Gtalk and we'll discuss.

**Comment by mnarewec** [comment]
@AAndharia yeah why us is it a CR ? There is no page break?

**Comment by AAndharia** [comment]
@mnarewec - You are right, but its not just about page break. we are not raising this as CR due to page break, its due to all other changes. When we make changes in iTextSharp, its time consuming for development because every change made needs to be verified by developer & QA and to do that, both have to follow & generate the PDFs. I hope that gives you clear idea.

I've created another issues with #200 . Please close this one if everything else is fine.

**Comment by AAndharia** [comment]
Also, please note we have also done a few enhancements for other tasks in CR 1.9 which were not actually bugs, but these are little bit more ... that's why.
