### ISSUE TITLE
Login page - create a presentable background

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#185]
Something like the login page of sales force (no video - just background image so it will be lighter to load)
https://login.salesforce.com/?locale=in

![image](https://cloud.githubusercontent.com/assets/10192106/8955765/0fa2eb3a-3633-11e5-8142-cf82211fb821.png)

1. Replace Blue Background with something like this (waves at the background ..refer image)
![image](https://cloud.githubusercontent.com/assets/10192106/8956627/1e9eb36e-363b-11e5-96db-814afcc7f214.png)

2. Replace the image in the box with this image. Its size is 4MB (BIG) but please re-size to fit the box. https://drive.google.com/a/kumulsoft.com/file/d/0B9T2hcAcxJgLSnVDajNzdVRITFk/view?usp=sharing

3. Make 'Learn More' to point to www.kumulsoftbilling.com/features/ and 'Contact Us' to point to www.kumulsoftbilling.com/contactus/

**Comment by AAndharia** [comment]
Do you have any image that you use for marketing KSB product which we can utilize on this page?

**Comment by mnarewec** [comment]
@AAndharia ,cc @jmervana Please use this image as background  as 'wave'

This is our branding image:
![kumulsoft brand](https://cloud.githubusercontent.com/assets/10192106/9025351/b804dac2-3944-11e5-85ab-f29be088f8ce.png)


And this is our business Card, if our can have the login page to be formatted/layout like this will be great.


![kumulsoft business card](https://cloud.githubusercontent.com/assets/10192106/9025362/531988a0-3945-11e5-94d4-1b7563cfd411.png)

**Comment by AAndharia** [comment]
1. In salesforce where it is dark-blue complete background...we'll use this new wave image you've just provided, and it would be repeated horizontally (behind the login box) to fill the screen.
1. Login box will have 2 section - left & right. 
 1. Left will be similar to existing login section
 1. Right will be the product image you've provided.

Please confirm my understanding.

**Comment by mnarewec** [comment]
1. Do not repeat new wave image..place just lay just above or below the login box.


2. yes

**Comment by AAndharia** [comment]
Ok. Thanks. We'll follow.

@jmervana - please estimate. If any questions, please discuss with me.

@mnarewec - please do not change anything in description from this point forward. If you do, please add a comment.

**Comment by AAndharia** [comment]
http://voormedia.com/blog/2012/11/responsive-background-images-with-fixed-or-fluid-aspect-ratios

try using this article for responsivness of background image.

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by mnarewec** [comment]
This is good but please replace the background with a blue color. The color code of blue is 0A9BCB

**Comment by AAndharia** [comment]
@mnarewec - If we set blue background, the background image will merge into it.Can you please suggest?

**Comment by mnarewec** [comment]
Remove the background image and only set the background color

**Comment by pasodariya** [comment]
Done Please Verify.

**Comment by Talmax** [comment]
This issue has been resolved.
