### ISSUE TITLE
Dashboard - Changes to Dashboard

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#186]
(1) Replace the current 'Aged Outstanding Bills Summary' with this table (format it like the goclio refer Amit). Rename it to **Outstanding Bills Summary**

![image](https://cloud.githubusercontent.com/assets/10192106/8956561/7a8ec43a-363a-11e5-8f8c-58c357ce9f9e.png)

[Amit: 29JUL] : Like this way...
![capture](https://cloud.githubusercontent.com/assets/2442925/8956899/bfce47be-3617-11e5-80a1-af7b6a785de0.PNG)

@AAndharia , cc @jmervana there should be another last  total row [Total Over Bills] at the bottom of that table summing the all three aging figures [count, total outstanding]  together
![image](https://cloud.githubusercontent.com/assets/10192106/8971676/f3354f0c-3695-11e5-80a4-830c34b4134f.png)

(2) the current 12 monthly outstanding graph  depends on *Total Outstanding Amount*. Change it and now it should depend on *Total Amount* and rename the graph to **Monthly Income Summary*. @AAndharia , @jmervana  please suggest and use a third party graph that can be show data both in offline (not connected to internet) and online (connected to internet).

(3) Change the 'Lawyers WIP Summary' to include an extra column showing the number of hours. Also show both the total of Amount and Hours at the bottom.

*Format all currency to have thousand separators and show current sign.*

**Comment by AAndharia** [comment]
I would recommend chartjs
* It is open source
* It doesn't use image at all, it just draws the charts with HTML/CSS

http://www.chartjs.org/docs/#bar-chart-introduction
http://www.chartjs.org/docs/#notes-license

Notes
* It is supported with HTML5 only (only modern browsers)
* Here what i've outlined is as per our understanding & knowledge of this tool. Please review it once from your end too, if it match all your expectations before you approve. If you have any questions, feel free to ask and we'll investigate for you and respond.

**Comment by mnarewec** [comment]
OK let's use this. Please confirm if it will work offline too?

**Comment by AAndharia** [comment]
@mnarewec - yes confirm, it would work without internet.

@jmervana - please analyze & estimate.

**Comment by AAndharia** [comment]
http://earlonrails.github.io/angular-chartjs-directive/ - we'll be able to use this directive and just modify the code.

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
This change has been solved.
![image](https://cloud.githubusercontent.com/assets/13091499/11202105/3f7a6e06-8d30-11e5-9e7c-44afd4d93b85.png)
![image](https://cloud.githubusercontent.com/assets/13091499/11202119/7f4c436a-8d30-11e5-8396-f827bd7f23ae.png)

**Comment by Talmax** [comment]
**Lawyers WIP summary**
The WIP hours should be converted to actual hours if using lawyers rate in bills setup. Please correct that.

**Comment by AAndharia** [comment]
@mnarewec - we are not storing hours in our database. so when showing WIP here in dashboard, should we use current setting of "Use Lawyer's Rate" - it wouldn't be accurate, because it may be different when they have submitted entry and accordingly their total amount is created. Please suggest. 

Also, i would recommend to create a new CR which stores Hours in timesheetentry tables.

**Comment by mnarewec** [comment]
Ok if it Lawyers Rate then convert Units to Hours. Yes I think we should store hours separately but that will be a different story.

**Comment by Talmax** [comment]
This issue has been resolved
