### ISSUE TITLE
Bill Generation >> Print Selected Draft/Final Bill

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#190]
1. Please rename the selected label for both Draft and Final Bill to 'Print Selected Draft Bill' or 'Print Selected Final Bill' respectively
2. Both should export directly the Bill to PDF.

![image](https://cloud.githubusercontent.com/assets/10192106/9047127/03a711c8-3a73-11e5-915c-18cf0f14648c.png)

**Comment by AAndharia** [comment]
@mnarewec  - label rename is not an issue, but converting to PDF directly would be a CR. Please suggest.

**Comment by mnarewec** [comment]
You will be already doing it and achieving it in issue #174 . Replicating it here should be not an issue.

**Comment by AAndharia** [comment]
in #174  we are just converting to Final Bill. CR will be for Draft bill.

**Comment by mnarewec** [comment]
The same PDF conversion/export routine is not used?

**Comment by AAndharia** [comment]
@jmervana - can you please justify as you justified me.

**Comment by mnarewec** [comment]
We don't mind taking it as a CR but will appreciate if its not costed as a
completely new routine because we all now that routine is already there to
export.

**Comment by AAndharia** [comment]
Yes, the additional cost will be only for any additional work required after re-using anything which is already there.

**Comment by AAndharia** [comment]
@jmervana - please analyze & estimate.

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
This issue has been resolved.
**DraftBill**
![image](https://cloud.githubusercontent.com/assets/13091499/11200809/71978cae-8d24-11e5-926c-510d7d7f3573.png)
**FinalBill**
![image](https://cloud.githubusercontent.com/assets/13091499/11200834/a268f188-8d24-11e5-97a3-2d5efdae5e1b.png)

**Comment by Talmax** [comment]
Approved
