### ISSUE TITLE
Rates used in Final & Draft Bills Generation should be based on Timesheet Rate

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#191]
Rates used in Final & Draft Bills Generation should be based on Time sheet rate and NOT on lawyers rate. That means if a lawyer works last week on K700 per hour and this week on K1000 per hour then it should list those separate late on the Draft Bill and Final Bills. Both at the Timesheet Entries section and also on the Professional Time Summary section.

**Comment by jmervana** [comment]
@mnarewec 

would you please explain in brief ?

**Comment by AAndharia** [comment]
@mnarewec - i've discussed this with Japan, here is my understanding. Please correct me if anything is wrong.

1. This change only requires in pdfs generated. 
1. In TimeSheet entry section, its already working. Please verify.
1. In Professional Time Summary, we should show entry for each different combination of Lawyer & Its rate. Meaning if a lawyer has worked for 2 different rates then 2 entries will be visible in professional time summary.

Now all above can be achieved very easily, the complex scenario is with multiple lawyers selection for timeshet entry.

1. At present we are not storing seperate rate for each lawyer at the time of time sheet entry. We just do the total of each selected lawyers rate and store it in timesheet entry.
1. if in professional time summary, we have to show each lawyer entry for each different rates (single or multiple lawyer selection mode) we must have to store rate along with each multiple selected lawyer.
1. multiple lawyers at present are stored in timesheet entry table - comma sperated as suggested by you, so storing the rates is not possible. Also, if we create new table to store this data, for any existing data of any existing installations can't be handled as we can't know what was the rate of the lawyer at the time of that time sheet entry made in past.

Waiting for your response.

**Comment by AAndharia** [comment]
As per our discussion with @mnarewec  on 19th Aug. we are including "Removing Multiple Lawyer Selection"  functionality entirely from entire application - code will be removed & logic will be changed wherever applicable.

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
This issue is resolved
