### ISSUE TITLE
Management > Files. Changes File Type and create new Bill Type

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#192]
1. Rename field 'File Type' label to 'Bill Type'. That will be on Files & Update Batch and also on the MstFiles table rename field FileType to 'BillType.

2. Create a new field called 'FileTypeId' in table MstFiles. It should have values from a new table that will be called 'MstFileTypes'

3. On the Data Entry/Display page arrangement, it should show File Type drop down list (Display File Type Sub Category), right after the File Number.  Special Requirement for File Type Drop down box is to show the Category and Sub Category on the same Drop Down List, user will only to be able select the Sub Category.

4. Additionally, this file type now appear on the Labels Report.

**Comment by jmervana** [comment]
@mnarewec 

as per my understanding,

1) File Type lable change to bill type means label highlighted in below image.
![image](https://cloud.githubusercontent.com/assets/7436116/9320722/e0b53a9c-457a-11e5-9fee-01027786cd85.png)

2) bill type is just label change functionality will not be change , isn't it?

3) what do you mean by category & Subcategory ? 

4) what is the use of file type category and sub category, just for display or any logic behind it ?

**Comment by mnarewec** [comment]
@AAndharia as per our gtalk.

**Comment by AAndharia** [comment]
As per our discussion on chat with @mnarewec on 19th Aug.

1. A new field named FileType should be added
2. This new field will bind data from master defined in #193 
3. Current file type labels & fields will be renamed to Bill Type as explained above in description.

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
This issue has been solved. see image.

Files

![image](https://cloud.githubusercontent.com/assets/13091499/11173447/5154846e-8c62-11e5-8d9a-ec3a81b238d8.png)

Update Batch

![image](https://cloud.githubusercontent.com/assets/13091499/11173979/59f073a6-8c69-11e5-86d1-695b13eb5f71.png)

Tables

![image](https://cloud.githubusercontent.com/assets/13091499/11174021/e8b81c88-8c69-11e5-8cc3-1831734227a9.png)

Data entry (files)

![image](https://cloud.githubusercontent.com/assets/13091499/11174316/7c26c8ea-8c6d-11e5-8f64-1b2f5a2575be.png)


file information label

![image](https://cloud.githubusercontent.com/assets/13091499/11174353/0e279ff8-8c6e-11e5-955c-83ff16dc0193.png)

![image](https://cloud.githubusercontent.com/assets/13091499/11174364/32b08c86-8c6e-11e5-9b06-01e89f4cb51b.png)

**Comment by Talmax** [comment]
Approved
