### ISSUE TITLE
Setup : Create a new component called File Types

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#193]
It features, including editable columns, etc, should be similar to 'Manage Chapters' in ZIMS. Refer image.  It will maintain new db table MstFileTypes (Id, Category, Sub-Category).
![image](https://cloud.githubusercontent.com/assets/10192106/9160134/42025e78-3f78-11e5-970c-939639663a71.png)

**Comment by jmervana** [comment]
@mnarewec 

are these file types loded in dropdown in manage file page ? is there any requirement for file type like if file type is fixed rate then we will have to fetch fixed amount.

![image](https://cloud.githubusercontent.com/assets/7436116/9320681/67bdc776-457a-11e5-8c17-83f8531e8658.png)

**Comment by AAndharia** [comment]
@mnarewec - few more questions

1. category & sub-category both are string fields? 
1. and both are mandetory? 
1. What is the rule for checking duplication to deny duplicate entries? 
1. we'll not allow to delete any record which is referred anywhere. correct?
1. what are the applicable permissions & how?

**Comment by AAndharia** [comment]
@mnarewec - should we create 2 seperate form for category & sub-category ... similar to Disbursement & Disbursement Type? I mean for creating sub category, you'll select category from left and add all sub categories for it. This would make it look similar across entire application. Please suggest.

**Comment by mnarewec** [comment]
Ok..yes please

**Comment by AAndharia** [comment]
@mnarewec  - let's discuss this on GTalk.
