### ISSUE TITLE
Setup >>Company Information. For the first time

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#195]
When wanting to setup company information for the first time, after selecting company logo and clicking 'Upload Logo' it is not saving everything i.e. company etc but just only the logo

**Comment by jmervana** [comment]
@mnarewec 

upload logo is not button to save data. you will have to click save button to save data.

**Comment by mnarewec** [comment]
@jmervana, Yes I know..I clicked Upload logo first and got this error.., because I was still entering data and not saving yet.

**Comment by jmervana** [comment]
@mnarewec 

I cannot reproduce any error on update logo button when no company data entered

**Comment by mnarewec** [comment]
@jmervana ping me and I will show.

**Comment by mnarewec** [comment]
We will take the step of saving other data first before uploading company logo.
