### ISSUE TITLE
Rename various tables in database and move fields

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#197]
1. Rename 'MstLawyers' to 'MstEmployees'
1. Rename 'LawFirm' to 'MstCompany'
1. Move fields 'FileNumberFormat' and 'UseTimeCodeDesc' and 'UseLawyerRate' to 'MstSystemDefaults' from LawFirm to 'MstSystemDefaults'
1. In MstLawyers rename field 'LawyerUserId' to 'EmployeeUserId'
1. Create a new field in MstClients and called it 'ClientType'
1. Rename MstReceipts to MstBankTransactions. Rename field PaymentDate  to TransactionDate. Rename PaymentType to TransactionMethod, and create new field TransactionType. I will update #215 to reflect this requirement

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by jmervana** [comment]
@mnarewec 

I have some few questions:

1. Rename 'MstLawyers' to 'MstEmployees' - in this , do you want to change in ui too ?
2. Create a new field in MstClients and called it 'ClientType' - is it textbox or dropdown in client screen ?

do you want to display these new fields anywhere ?

**Comment by Talmax** [comment]
This issue has been resolved.


![image](https://cloud.githubusercontent.com/assets/13091499/11175200/4dccbcc6-8c7b-11e5-9164-73f6bdc915ae.png)

**Comment by Talmax** [comment]
Approved
