### ISSUE TITLE
Use google font in billing reports in dropdown

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#198]
@AAndharia 

I have discussed with Marsh on Gtalk. He want me to add google font as an option in font style dropdown.

currently Draft Bill and Final Bill have option to select Font Style. We have added 5 to 6 font family there but Marsh want me to add Google Font too. I have to check this font family with licensing and confirm that can we use it or not ? if we can I will do that.

This is CR.

**Comment by AAndharia** [comment]
@jmervana - please add requirements in description above.

**Comment by AAndharia** [comment]
@jmervana - please analyze licensing for putting google fonts within our solution ... because KBS is not using internet. If licensing support this, please provide me estimate. If not, then please put licensing link here and assign back to Marsh to decide.

**Comment by AAndharia** [comment]
https://developers.google.com/fonts/faq?hl=en

@mnarewec - according to link above, Google Fonts can be downloaded to our local server. I was unable to find detailed license. Please review and confirm, so that we can proceed.

**Comment by jmervana** [comment]
As per discussion on 25th Sep with Marsh. he has understood google license and approved to use this method to download the fonts and use it inside solution to print pdf only (fonts not to be used for any web page).

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
This issue has been solved.

![image](https://cloud.githubusercontent.com/assets/13091499/11174915/3a908484-8c77-11e5-91cf-78608d9f49cf.png)

google fonts
![image](https://cloud.githubusercontent.com/assets/13091499/11174932/5f6a8a16-8c77-11e5-8526-83450bb6fe7b.png)

**Comment by Talmax** [comment]
Approved
