### ISSUE TITLE
Trust Account Statement >> Show Client Name & Page Wise Header Info

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#199]
1. Change label as per image below
![image](https://cloud.githubusercontent.com/assets/10192106/9354433/b66b42d8-46b3-11e5-8b86-954954015a4a.png)

2. Force Page break when change of client, i.e. exactly like Statement of Account., so it prints new header, when the client name changes.

**Comment by AAndharia** [comment]
@jmervana - please analyze & provide estimation.

**Comment by mnarewec** [comment]
Page number must restart for new client (page break)
![image](https://cloud.githubusercontent.com/assets/10192106/9755227/a87075ac-5713-11e5-9a79-535e12934df2.png)

**Comment by mnarewec** [comment]
This has been resolved.
