### ISSUE TITLE
File Ledger to Properly Formatted

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#200]
1. New File or Next file number should force a page break, and the new page should print header (logo etc)

2. Include the text 'File Ledger' with File Number, refer image below
![image](https://cloud.githubusercontent.com/assets/10192106/9352594/d072c6f0-46a5-11e5-8e72-c9c62f8b6ff0.png)

3. Format the hours correctly, see image below
![image](https://cloud.githubusercontent.com/assets/10192106/9352622/0f99dd32-46a6-11e5-9e52-3769c412b532.png)

4. Rename the section 'Trust Fund Info' to 'Trust Account Details'
![image](https://cloud.githubusercontent.com/assets/10192106/9352794/39bcc5f6-46a7-11e5-9db8-4181f1af5ab3.png)

5. Please make changes as per image below.
![image](https://cloud.githubusercontent.com/assets/10192106/9353452/c73e10d4-46ab-11e5-9e34-9916b439e611.png)

**Comment by jmervana** [comment]
@mnarewec 
I have implemented it

**Comment by mnarewec** [comment]
Uable to test it because we cannot export to PDF

**Comment by mnarewec** [comment]
This has been resolved.
