### ISSUE TITLE
Reports >> File Reports>> File information Label

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#202]
Report name should'nt be "File Leger" it suppose to be "File Information Label"

1. Change the Report name to File Information Label. Refer to the image below

![image](https://cloud.githubusercontent.com/assets/13091499/9456140/2bbbc7bc-4b17-11e5-9f22-a0c944b0fc6f.png)

2. Run time error. when export the files to PDF, this errors occurs.. refer to the image below.

![image](https://cloud.githubusercontent.com/assets/13091499/9456267/95008586-4b18-11e5-973e-fedec84c3813.png)

**Comment by jmervana** [comment]
@Talmax 
label will be changed but 2nd error I cannot reproduced.

**Comment by mnarewec** [comment]
WE clear cache and restart IIS but this issue still persist.

**Comment by AAndharia** [comment]
We are unable to re-produce this at all. Can you please suggest the steps to re-produce this?

**Comment by mnarewec** [comment]
Click on Export Button.. that's all.

**Comment by AAndharia** [comment]
strange ! looks like something is wrong with the release. Will investigate.

**Comment by mnarewec** [comment]
This has been resolved.
