### ISSUE TITLE
Prepare full db script for new client installation

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#204]
1. One single db script file, after executing it the db must be up & ready to use. Don't include Central DB.
2. After this, everytime you make any changes in script, keep your changes within solution with version number files so in future no such requirement arise.
3. Script file should include any default data required to make system running - especially for menu & default super user. Test it properly before sending to @mnarewec .

**Comment by AAndharia** [comment]
@mnarewec - i've updated CR sheet with estimation.

**Comment by mnarewec** [comment]
Ok Approved for payment. COnsider it close
