### ISSUE TITLE
Management >> Files >> Subject Matter: Word Characters are too Short

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#211]
Refer to the image below, Some court matters are sentence and long and can not be saved causing the run time error. Please increase the characters in Subject matters. Increase size of subject Matter field to Max.

![image](https://cloud.githubusercontent.com/assets/13091499/9841310/68c2387e-5ae1-11e5-94bd-0f57bd3fbe61.png)

**Comment by AAndharia** [comment]
@mnarewec  - what should be the idea length this field should have?

**Comment by mnarewec** [comment]
max (unlimited)

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
This issue has not been solved.

**Comment by AAndharia** [comment]
@Talmax - is this suppose to be assigned to me?

**Comment by Talmax** [comment]
@AAndharia - Yes. We are still experiencing issue on subject matter due with the short field character. See image with an incomplete word "Street".

![image](https://cloud.githubusercontent.com/assets/13091499/11176329/a30a816c-8c87-11e5-9e32-2ce13aea39ad.png)

**Comment by pasodariya** [comment]
Done Please Verify

**Comment by mnarewec** [comment]
This has been resolved.
