### ISSUE TITLE
BIlling >> BIlls Generation. Outstanding amount not reduce the 2nd time when making payment via Trust Account

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#212]
Outstanding amount not reduce when making payment the 2nd time via Trust Account on the same bill.

![image](https://cloud.githubusercontent.com/assets/10192106/9868489/9f2b3bb4-5bbc-11e5-84fe-3308b4ad1cb8.png)

**Comment by AAndharia** [comment]
Done. Please verify.

**Comment by mnarewec** [comment]
This issue is resolved  but when you have two bills for same file it appears at both. I will add a new requirement to include bill id in trust fund transactions so that payment can be separated for each bill. New requirement will also include interface change to Trust Account management
