### ISSUE TITLE
Draft Bill >> Final Bill >> Client Contact Name and File Contact Name Should not be repeated on the Printed Bill

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#213]
The rule is on a Bill the Client address when printed should be as follows
* 1st Line - Contact Name base on File, if no contact name on File then,
Contact Name Base on Client, if No Contact Name on Client, then use client
name.
* 2nd Line - Client Name if not used in Line 1 above. If client Name is
used in Line 1 above this line should be ignored.
3rd-5th line etc - Base on the Postal Address - each line is separated by a
comma.

that is the rule
Refer to the image below

![image](https://cloud.githubusercontent.com/assets/10192106/10091608/07b742f6-6381-11e5-89e1-95a63a1c7ad9.png)

**Comment by mnarewec** [comment]
The rule is on a Bill the Client address when printed should be as follows
* 1st Line - Contact Name base on File, if no contact name on File the,
Contact Name Base on Client, if No Contact Name on Client, then use client
name.
* 2nd Line - Client Name if not used in Line 1 above. If client Name is
used in Line 1 above this line should be ignored.
3rd-5th line etc - Base on the Postal Address - each line is separated by a
comma.

that is the rule

**Comment by jmervana** [comment]
@mnarewec - this will be a CR. We have implemented as you requested earlier, this Rule is just made now. Please confirm.

**Comment by mnarewec** [comment]
This is NOT a CR. this rule has been ever since there.

**Comment by AAndharia** [comment]
@mnarewec  - can you please suggest when did this rule came? I talked with Japan, this has never been conveyed to us.

**Comment by mnarewec** [comment]
During Billing Manager. Try print Bills in V 1.6 etc and you will see.

**Comment by AAndharia** [comment]
I mean this requirement was discussed with Japan on chat or given in github... we'll have to find out if it was ever given as requirement or not.

**Comment by jmervana** [comment]
@mnarewec - we have to use 3rd to 5th line comma seperated from Client Postal Address. But Client Postal address is a multiline textbox. How do you need us to split that single value in 3 lines? based on what logic? Please suggest, and will do accordingly.

**Comment by mnarewec** [comment]
@AAndharia , I tested different scenerio and it looks ok. Please remove the blank line between contact names and the postal address. 
![image](https://cloud.githubusercontent.com/assets/10192106/10175370/c72b7860-6731-11e5-81c1-cc3cf8e438ad.png)

**Comment by AAndharia** [comment]
@mnarewec - we are unable to re-produce this at our end. Tried all different options.

**Comment by mnarewec** [comment]
In manage client > enter contact name as : Marsh Narewec, CEO
Do not enter anything in Manage File > Contact field.

**Comment by AAndharia** [comment]
This is done. Please review in 1.9.9

**Comment by mnarewec** [comment]
This issue has been resolved.
