### ISSUE TITLE
Changes to Banking >> Receipt Bills Page

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#214]
There is a change to the way we want to present data at the receipt Bills Page. We want to make Receipt bills page to show the Receipt Transactions (currently in v.1.9.7  its the Outstanding Bills tab). Users should be able to see the list of transactions and print receipts out using this page.

Here is the sample of the page. This should give you some ideas.
![banking transactions page](https://cloud.githubusercontent.com/assets/10192106/10091748/54859faa-6382-11e5-81a2-c11881c92062.png)

**Comment by AAndharia** [comment]
Scope of work we considered in estimation
=================================
1. On Banking > Receipt Bills page remove Add Receipts Tab
2. Rename Outstanding Bills tab to Transactions
3. Move Add Receipt button to Transactions tab at bottom
4. Data in the grid in Transactions tab will remain as it is - same fields/same grid headers. Everything is same. No Change. Print option will remain same as well.

Please confirm.

**Comment by mnarewec** [comment]
Yes

**Comment by AAndharia** [comment]
1. Ok. We'll remove client on left and Transactions tab will show data of all the clients
2. Ok.
3. Ok.
4. Ok .. its just that it will now be shown for all the clients (paginated grid).

**Comment by mnarewec** [comment]
Yes. Paginated grid.

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
Approved
