### ISSUE TITLE
Changes to Banking >> Add Receipt Info

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#215]
Currently the Bill Receipt Page, have feature to allocate/made payment. We would like to move that feature (currently in version 1.9.7  its the **Add Receipt** tab) into the Add Receipt Info pop up window page.

Refer image below for more information. 
![banking transactions-receive money](https://cloud.githubusercontent.com/assets/10192106/10091835/48fc796e-6383-11e5-838f-793f2a918b4e.png)

**Comment by AAndharia** [comment]
#### Few questions ####

1. What is transaction type field? is that a textbox?
2. What is type field in new screen you attached?
2. Receipt Reference will not be editable by user - same as current functionality - correct?
3. Amount field will not be there, it will be calculated based on allocated amount - correct?
4. When user click Add Receipt, he will always has selected a client already from left side client selction list. when we'll open add receipt popup, we'll select that client by default and load his outstanding bills for allocation. This dropdown for client selection will only have clients which has at least one oustanding bill (unlike left menu) and user can change the client from dropdown and everything will be reset (except transaction date). 

Please answer/confirm.
5.

**Comment by mnarewec** [comment]
so where is our existing Receipt Type field?  **new field is transaction type. Existing field Payment Type will be still there for to capture Cash/Cheque/Direct Deposit etc.
also the new other payment field...u need it in bill or payment?
there? There is no new payment field.

**Comment by AAndharia** [comment]
As per our discussion on chat, at present we'll disregard Other Payment field. Its not part of our work at present.

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
This issue has been solved.

![image](https://cloud.githubusercontent.com/assets/13091499/11199514/e69f3a7a-8d19-11e5-8953-20e58145210a.png)

**Comment by Talmax** [comment]
Approved
