### ISSUE TITLE
Changes to Billing >> Outstanding Bills

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#216]
1. Rename Outstanding Bills menu item to 'Bills'
2. Rename Outstanding Bills Page to 'Bills'
3. On the same data grid create two tab. Outstanding tab will show current data i.e. outstanding bills. History tab will show paid bills

![image](https://cloud.githubusercontent.com/assets/10192106/10092104/501c9c08-6386-11e5-91b0-7c34e13c3a65.png)

**Comment by AAndharia** [comment]
1. what are the fields to be shown in grid of paid bills in history tab?
2. is there any print functionality in history tab? if yes, please provide format of that pdf to be printed.

**Comment by AAndharia** [comment]
1. So history tab will show bills which are fully paid - am i right?
2. So history tab will show same fields as out standing tab grid. Instead of outstanding amount, we'll show paid amount which will be same as Total Amount - correct?

**Comment by jmervana** [comment]
Requirements locked, pdf printed.

**Comment by Talmax** [comment]
This issue has been solved.
