### ISSUE TITLE
Major Issue : Outstanding Amount not Correct when a discount is added.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#217]
The total Charge on the Bill is correct refer figure 1 below. However,the Total Amount and Total Outstanding amount on the page or database is NOT correct - refer figure 2 below

Figure 1 (Correct Figure)
![image](https://cloud.githubusercontent.com/assets/13091499/10093374/d730ffdc-6394-11e5-9f3e-629716e8b54f.png)

Figure 2 (In correct Figure)
![image](https://cloud.githubusercontent.com/assets/13091499/10093390/1de1266e-6395-11e5-917a-8fad2c8220a0.png)

**Comment by jmervana** [comment]
@mnarewec, @Talmax - can you share your screen tomorrow. I need to see actual data entered and then generate report and see ... for me it looks this is not error related to report, its related to data entered .. i mean some other error which is generated while entering data.

**Comment by mnarewec** [comment]
@jmervana , @AAndharia  we have tried on several bills and it only happens on Discount Bills. We also noticed that the varied (Difference) amount is actually the GST portion of the Discounted amount. Therefore, this is not a database or a data entry issue. It is a logic/business rule. Your charge out should be same as the Total Amount and the Total Outstanding.

Your calculation for the charge out is correct but your calculation for the Total Amount and Outstanding Amount IS NOT CORRECT, it also include the Tax portion of the amount that has been discounted. Please correct this issue ASAP before end of this month in preparation for clients running new bills.

**Comment by AAndharia** [comment]
Done. Please verify.

**Comment by mnarewec** [comment]
This has been resolved.
