### ISSUE TITLE
Major Issue : Both Final and Draft Bill not showing correct Professional Time Summary Value

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#218]
The total amount (value) in the each item under Professional Time Summary is not showing correct figure. This affects **both Twivey and Bradshaw** format of Bills. Refer below image

Figure 1
![image](https://cloud.githubusercontent.com/assets/13091499/10093432/bcd8afd0-6395-11e5-88eb-342c6781bbd0.png)

Figure 2
![image](https://cloud.githubusercontent.com/assets/13091499/10093442/d1acc3c4-6395-11e5-9859-a5e06bb62903.png)

**Comment by jmervana** [comment]
@Talmax - professional summary in both of the figures are showing correct data. for example 6.70 X 600 = 4020.

Also, you've highlighted some other values apart from professional summary. Don't know why? Is it relevant?

**Comment by AAndharia** [comment]
We made some changes to the report as per discussion with @mnarewec . Please verify.

**Comment by mnarewec** [comment]
This has been resolved.
