### ISSUE TITLE
Bill Generation >> Creating new batch not following Minimum WIP rule

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#219]
When I entered K10,000 as Minimum WIP its picking everything every files. It should only pick files which have WIP 10,000 or more.

![image](https://cloud.githubusercontent.com/assets/10192106/10205648/ce94b664-6805-11e5-90f0-34af586f6e2d.png)

**Comment by AAndharia** [comment]
It looks like Min WIP Amount is working fine. Files with Fixed Rate will be visible always regardless or WIP Amount as per requiements. Do you want to change?

**Comment by mnarewec** [comment]
Thank you Amit for point this out. This is not an issue.
