### ISSUE TITLE
Changes to Trust Account management page. the browses/search page

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#220]
We will have to change it the same way we change Banking > Receipts. So the current page will have to be modified and change. 

**1. This is how the main Trust Account Page should look like**
![image](https://cloud.githubusercontent.com/assets/10192106/10208121/6b224d6c-6814-11e5-95d6-381c86043862.png)

1. Include new field bIll number to capture bill numbers of pay bills transactions
2. Should be able to print deposit receipt of current and past transactions

**Comment by AAndharia** [comment]
So as per my understanding.

1. Remove tabs Transactions & Pay Bills
2. Show all Bill & DEP transactions together in single grid
3. For Transaction with type Bill, we show option to print & also show bill number
4. For Transactions with type Dep, Bill number & print column will not have anything.

Please confirm.

**Comment by AAndharia** [comment]
So, Print button will not appear for Bill type, but will appear for Dep type. and it would print deposit receipt. Ok. Got it.

**Comment by mnarewec** [comment]
File and client filters on top of the data grid will do but NOT on the left side.

**Comment by AAndharia** [comment]
As per our discussion over chat. few changes

1. We'll show all the transactions by default (regardless of file/client/lawyer). 
1. Entire left filter section that exists right now will be removed.
2. Search on grid records will be on Transaction Date & Keyword
3. Keyword will search wildcard (contains search) on File Number, Bill Number, Deposit Number & Client Name.
4. Show client name in grid as column

**Comment by AAndharia** [comment]
@mnarewec - just to clarify here, our new requirement of showing bill number will work for only bills generated after this CR published. For any older data/records/transactions, bill number will not be visible because it was not stored earlier and it was part of just the note.

**Comment by Talmax** [comment]
This issue has been solved.
![image](https://cloud.githubusercontent.com/assets/13091499/11201624/5b315c04-8d2b-11e5-9239-302c42f072b2.png)

**Comment by Talmax** [comment]
Approved
