### ISSUE TITLE
Changes to Trust Account >> Pay Bills

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#221]
Pay bills will now be a pop up window like this
![image](https://cloud.githubusercontent.com/assets/10192106/10208891/eed3953a-6819-11e5-9cfd-bdd21c3d55ca.png)

**Comment by AAndharia** [comment]
1. Selecting a client is mandatory
1. Selecting a file is also mandatory, and that will only be possible after selecting a client.
1. Selecting a file will show Trust Fund Amount & Grid below it for the bills relevant to those files.
1. Notes will be stored in same database field as note for DEP type transaction is stored. Note will appear automatically same as now and not editable by user.

Please confirm.

**Comment by Talmax** [comment]
This issue has been solved.See image below

PayBills

![image](https://cloud.githubusercontent.com/assets/13091499/11174747/9cdb5f9a-8c74-11e5-9d77-fa1c531c9554.png)

![image](https://cloud.githubusercontent.com/assets/13091499/11174663/28aa57da-8c73-11e5-8b4e-3667e29502c1.png)

**Comment by Talmax** [comment]
Approved
