### ISSUE TITLE
Changes to Trust Account >> Change in Deposit Pop up

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#222]
Include client name and file number in the Deposit pop up so user can select client and file number to do deposit against
![image](https://cloud.githubusercontent.com/assets/10192106/10209087/7b55525e-681b-11e5-9484-49f33ee20799.png)

**Comment by AAndharia** [comment]
1. Here selecting a client is mandatory
2. User can enter one and only one file number, that too after selecting the client.
3. File number is also mandatory

Please confirm.

**Comment by Talmax** [comment]
This issue has been solved.see image

![image](https://cloud.githubusercontent.com/assets/13091499/11175550/20804464-8c7f-11e5-9a08-ebe6527c3026.png)

**Comment by Talmax** [comment]
Approved.
