### ISSUE TITLE
Closed Files >> Closed Files should be in sequence 

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#224]
Closed files should be well numbered. its should be  on sequence and not like how its shows in the image below..

![image](https://cloud.githubusercontent.com/assets/13091499/10505900/79f05644-7355-11e5-932d-c6eea9933b69.png)

Sample image of how the closed files should be arranged.

![image](https://cloud.githubusercontent.com/assets/13091499/10506218/aebcac80-7358-11e5-9631-72e589e3780d.png)

**Comment by AAndharia** [comment]
@Talmax - can you please let us know more about what's the problem here?

**Comment by Talmax** [comment]
@AAndharia  - when we closing the files, the file report captures all the Closed file numbers as 15/0001 etc..as it should be in sequence form from the first closed file on on wards.

**Comment by AAndharia** [comment]
what is the version of the application?

**Comment by Talmax** [comment]
Its happening in version 1.9.10

**Comment by mnarewec** [comment]
@AAndharia, this is a bug and needs to be addressed in this release. Please comment otherwise.

**Comment by AAndharia** [comment]
yes, we already found this and already fixed by dev team. would be resolved in next release. do you think there will be any existing data? or we should not worry about it for now?

**Comment by AAndharia** [comment]
handling any existing data is not possible and hence not done.

**Comment by Talmax** [comment]
This issue has been solved
