### ISSUE TITLE
Time sheet >> Add Entry; Files of a Selected lawyers should be capture on File filed.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#225]
From the the lawyers list on the timesheet entry, File should allow all the active files to appear on the files field. Refer to the image below.

![image](https://cloud.githubusercontent.com/assets/13091499/10531453/3d349062-73f5-11e5-9fed-1c24b2c4c590.png)

This format should be captured on file filed... Refer to the the image below

![image](https://cloud.githubusercontent.com/assets/13091499/10531905/e6ff9e48-73fa-11e5-98ed-473677f41414.png)

 
From Setup >> Billing Defaults; There should be another checked box called " Include Seleted Lawyers Active Files in Timesheet Entry". This will allow list of active files of a Lawyer. Refer to the image below.

![image](https://cloud.githubusercontent.com/assets/13091499/10531626/872c2642-73f7-11e5-9abd-dccf935d343c.png)

**Comment by mnarewec** [comment]
@Talmax , Multi-Lawyers requirement will be taken out in the next release CR 1.10. There is no need for this requirement. A lawyer can work on ANY files and not necessary their own.

@AAndharia ,ignore this requirement

**Comment by mnarewec** [comment]
I am closing this issue.
