### ISSUE TITLE
12 Monthly Outstanding Bills Graph is incorrect >> Bill Graph Data should based on "Period End Date" and not on "Batch Creation Date"

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#226]
When creating a new "BATCH" to run a period end bills (on Monthly bases), the data should be based on Period end date and not on Batch creation date. If it is October bills and Batch created on November, the total on the graph should be display on October.  refers to the image below.

![image](https://cloud.githubusercontent.com/assets/13091499/10960612/c7532d7c-83d0-11e5-9139-37e404eee74f.png)

Graph
![image](https://cloud.githubusercontent.com/assets/13091499/10960320/91bea156-83cf-11e5-80ff-f2a476335824.png)

**Comment by mnarewec** [comment]
@AAndharia , as you can see in the above image provided, the Bills where Generated in November but they belong to OCT because their period end date was '31-10-2015', therefore on the Graph the bar should be on the OCT. 

Please rectify that.

**Comment by AAndharia** [comment]
Ok. Will be taken care in next release.

**Comment by Talmax** [comment]
This issue has been solved
