### ISSUE TITLE
File Reports >> Closed File >> All the print pages are blank

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#235]
When printing this report, all the pages are processed being blank. See image below

![image](https://cloud.githubusercontent.com/assets/13091499/10719732/e8559f9a-7bd9-11e5-9c23-b4e8f497ed81.png)

**Comment by AAndharia** [comment]
@mnarewec  -  please check all configuration is correct. We don't have any such issue ever, and unable to re-produce this as well. Assigning back all the errors to @Talmax back.
