### ISSUE TITLE
Correct Change Password Page

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#242]
Make corrections as per the image below.
![image](https://cloud.githubusercontent.com/assets/10192106/11008553/fb165524-851c-11e5-9cb1-b3df70bfbab1.png)

**Comment by pasodariya** [comment]
Done. Will be sent in next release.

**Comment by Talmax** [comment]
This issue has not been solved.

**Comment by pasodariya** [comment]
Done Please verify.

**Comment by Talmax** [comment]
This issue has not been resolved.

The client code must not be editable, it must be hard coded to current client code as per Login page.

![image](https://cloud.githubusercontent.com/assets/13091499/11434010/61bd6642-9511-11e5-80f1-49d0a5ad6d12.png)

**Comment by Talmax** [comment]
This issue has been solved
