### ISSUE TITLE
Reset Password Email Message correction

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#243]
1. Please make corrections as per the image below
![image](https://cloud.githubusercontent.com/assets/10192106/11008792/96a2399e-851e-11e5-9729-fc9b1863a97b.png)
2. When clicking on the link provided, it went direct to the main system without giving the opportunity for user to confirm new password.

**Comment by AAndharia** [comment]
@mnarewec - I don't understand 2nd point, can you please elaborate?

**Comment by pasodariya** [comment]
Done. Will be sent in next release. waiting for answer on 2nd point.

**Comment by AAndharia** [comment]
Still waiting for your response on 2nd point.

**Comment by mnarewec** [comment]
I think it's because we were getting the browser to remember our passwords so after we changed our password right thru it. Will try again and advise.

**Comment by mnarewec** [comment]
This is resolved.
