### ISSUE TITLE
Reset Password Page correction

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#244]
please make correction as per image below
![image](https://cloud.githubusercontent.com/assets/10192106/11008846/e207c6ce-851e-11e5-865b-014b2c887241.png)

**Comment by pasodariya** [comment]
Done. Will be included in next release.

**Comment by Talmax** [comment]
This issue has not been solved. see image.

![image](https://cloud.githubusercontent.com/assets/13091499/11083503/f4a9a2d8-887b-11e5-90a6-f6bc3583d8c6.png)

**Comment by Talmax** [comment]
This regard my comments above. This issue has been resolved.
