### ISSUE TITLE
Reverse Engineering to Generate data for two Banking tables

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#246]
1. Reverse engineering of Bill Receipts to repopulate the new MstBankTransactions table and at the same time generate data for TrnBankTransactions.The good think is there are ONLY Invoice Receipts i.e. Bils Receipt  data to do re-engineering.

**Comment by AAndharia** [comment]
@mnarewec - can we discuss the formula of re-engineering? I understand you may not be aware with db table structures fully, but if you can explain screen by screen, that too would be enough. Just put something to start with and i'll keep adding.

**Comment by AAndharia** [comment]
I think you can close this issue, because in #240  we'll be doing this already, while changing the structure we must have to do the reverse-engineering of data too.
