### ISSUE TITLE
Management >> Trust Account >> Pay Bills >> Currency Separator or the comma.

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#249]
Total amount is showing as a whole number. There should be a comma to separate the currency numbers in values. see the image.

![image](https://cloud.githubusercontent.com/assets/13091499/11080673/e3bfb8a0-8861-11e5-8686-5ccb110dc066.png)

**Comment by pasodariya** [comment]
Done Please Verify.

**Comment by Talmax** [comment]
This issue has been resolved
