### ISSUE TITLE
Billing >> Final Bills. Payment(s) Received section is not correctly calculating bills

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#258]
This section should only show Payment(s) Received for current bill only and not any other bills under that same file.

**Comment by mnarewec** [comment]
Talmax this is not the issue we identified yesterday.

**Comment by AAndharia** [comment]
@Talmax  - can you please put the relevant issue # of the requirement doing this,.

**Comment by mnarewec** [comment]
@AAndharia , this is a bug.

**Comment by mnarewec** [comment]
The fix works for new Receipts from Both Trust Fund  Bank receipts but when printing existing Bills which have bank and trust fund receipts, its not showing the payment receipts.

**Outstanding Bill with Partial Payments**


**Final Bill Not showing Receipts**

**Comment by AAndharia** [comment]
@mnarewec - is this bill with discount? If so, its the problem with GST which wouldn't be fixed until this CR. If this is not the bill with discount, we have tried more than 10-15 bills at our end but none of them showing this problem. Can you please advice?

**Comment by mnarewec** [comment]
@AAndharia, I believe this is because of the Billid is null in TrnFilesTrustFund

**Comment by mnarewec** [comment]
This issue is now closed.
