### ISSUE TITLE
Small Changes to Bradshaw Bill Format

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#262]
Please make changes as per the attached imaged
![changes to bradshaw bill format](https://cloud.githubusercontent.com/assets/10192106/11489900/53f019f4-981f-11e5-86cc-85c76c37db11.jpg)

**Comment by AAndharia** [comment]
Locked Requirements. Sent Estimation. Printed PDF For future reference.

**Comment by mnarewec** [comment]
This is resolved and closed.
