### ISSUE TITLE
File >> Instruction Date and Creation Date

### ISSUE THREAD

**Issue by Talmax** [AAndharia/PSB#263]
When creating a file, the instruction date and the creation date shows **dd/mm/yr** and when printing the same file, instruction date and the creation date shows **mm/dd/yr**. Please fix this issue. See image.

**File view**
![image](https://cloud.githubusercontent.com/assets/13091499/11551868/39d92adc-99c9-11e5-8ecd-4e3b2a68beff.png)

**Print view**
![image](https://cloud.githubusercontent.com/assets/13091499/11551895/6b6757a4-99c9-11e5-8ad0-a4b2af4d839f.png)

**Comment by mnarewec** [comment]
The correct date format should be dd/MM/yyyy

**Comment by Talmax** [comment]
This issue has be solved
