### ISSUE TITLE
Credit Terms

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#265]
1. In System Defaults create a new field to capture credit terms. It should be an integer field. The default value is 30

2. Modify Bill Format # 1 and replace the highlighted text with the value from point #1 

![image](https://cloud.githubusercontent.com/assets/10192106/11583386/d37855b0-9aa4-11e5-8cdb-eeb1d69c93e3.png)

**Comment by AAndharia** [comment]
Locked Requirements. Sent Estimation. Printed PDF For future reference.

**Comment by Talmax** [comment]
This issue has been resolved
