### ISSUE TITLE
Box inf final bill pdf is wrong

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#266]
@pasodariya , @nirupasojitra - please both of you ensure all reports are up to the mark and nothing else is affected due to recent changes of 1.11

**Comment by AAndharia** [comment]
![image](https://cloud.githubusercontent.com/assets/2442925/11707953/1963ff36-9f30-11e5-8d4c-e8a041ce3dc6.png)

**Comment by AAndharia** [comment]
Also a uploading a valid logo failed

**Comment by AAndharia** [comment]
![2015-12-09](https://cloud.githubusercontent.com/assets/2442925/11708802/0aa653ec-9f38-11e5-87ac-8740c67af485.png)

**Comment by mnarewec** [comment]
This has been resolved.
