### ISSUE TITLE
Bills and transactions made by Trust Fund should be capture in the Receipt Bills

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#45]
Like our current system

**Comment by mnarewec** [comment]
This issue is not resolved

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Here we have different fields in list of receipt bills like all the info we show is related to receipt we create. (UI & list view changed in CR for make partial payment)
If you want to capture trust fund 
what should be come instead
1. Receipt Date
2. Amount
3. Receipt Reference
4. Receipt Type
5. Receipt Detail

**Comment by mnarewec** [comment]
This will be like a new CR so disregard
