### ISSUE TITLE
There should be Grand Totals Shown on ALL Reports except for

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#46]
Except for -- Lawyers Income, Bills (Draft & Final) and Client Statement --

Current system have grand totals on all reports except the ones mentioned above

**Comment by mnarewec** [comment]
This issue is not resoled.

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
This issue is confirmed resolved.
