### ISSUE TITLE
Bill Generation, default page should be the Billing Batch page

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#47]
And Completed Billing Batch Page should not have the check box (or the check box should be READ ONLY)

Like the current system

**Comment by mnarewec** [comment]
This issue is still no resolved.

**Comment by jmervana** [comment]
@AAndharia , @mnarewec 
This is an issue and it is resolved

**Comment by mnarewec** [comment]
Confirm This issue is resolved.
