### ISSUE TITLE
Dashboard 12 monthly Outstanding Bill Graph

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#49]
As per my requirement..it should show 12 rotating months.. that means for Jan 2015,it should Feb 2014, March 2014 - Dec 2014,and Jan 2015

**Comment by AAndharia** [comment]
@jmervana - please review if this is a bug or CR and inform me.

**Comment by jmervana** [comment]
@AAndharia 
As per email for requirement,
requirement is "12 Monthly Outstanding Bills bar graph".

**Comment by AAndharia** [comment]
@mnarewec - this is never been a requirement to show 12 rotating months data...but we'll not consider this change as CR.

@jmervana - please make this change and include in next release.

**Comment by mnarewec** [comment]
Done thanks
