### ISSUE TITLE
Dashboard - Header label

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#52]
Replace label Kumulsoft Billing System with the Name of the Firm.  Raised with Japan to be released in Release # 7 but that did not happen

**Comment by AAndharia** [comment]
@mnarewec , this is working at our end, can you please double check that you are looking at correct release? If so, assign this issue back to @jmervana.

**Comment by mnarewec** [comment]
Release 8.0 is still the same, Please @jmervana  check it out

**Comment by AAndharia** [comment]
@jmervana  Please have this resolved with Marsh asap. Ping him on gTalk.

**Comment by mnarewec** [comment]
There has been misundestanding. I want this (highlighted) to be changed
![image](https://cloud.githubusercontent.com/assets/10192106/5893754/07f8ab96-a53c-11e4-95e7-19b63f875ce6.png)

**Comment by jmervana** [comment]
@mnarewec  , cc @AAndharia 
Done

**Comment by mnarewec** [comment]
This has been resolved.
