### ISSUE TITLE
Login screen - Client Code should have a default value

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#53]
So that user does not key it every time. Raised with Japan to be released in Release # 7 but that did not happen

**Comment by AAndharia** [comment]
Marsh, can you please check if you have specified clientcode in web.config as per instructions sent in email? If Yes, and still this is not working, please assign us back.

**Comment by AAndharia** [comment]
​In "appSettings" section of web.config file, following key - value should be added.
 key="ClientCode" 
value="​value you want to set as default code"

**Comment by mnarewec** [comment]
Sorry did not see the intruction but just now show it. Its working
