### ISSUE TITLE
Disbursement Entry - Add Record

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#55]
1. As soon as Disbursement Entry page is shown, the focus should be on entry date
2. Cannot tab on Read-Only fields 
3. When submit button is pressed and execute focus should immediately go back to Entry Date

 Raised with Japan to be released in Release # 7 but that did not happen

**Comment by jmervana** [comment]
1. completed.
2nd & 3rd cannot reproduced.

**Comment by mnarewec** [comment]
Confirmed Done
