### ISSUE TITLE
Report - Client Statement - Export to PDF Progress

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#56]
Export to PDF is has a big delay and does not show download progress as 'Bills Report'. Sometimes it causes chrome to crash.

**Comment by jmervana** [comment]
@mnarewec 
we need to discuss about it.

**Comment by mnarewec** [comment]
Talked to amit already. @AAndharia @jmervana

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
There is already a gif image loaded and you cannot click at any link during this process.

**Comment by mnarewec** [comment]
This has been resolved.
