### ISSUE TITLE
Dashboard Security

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#58]
Roles who does not have access to Dash Board are still seeing Dashboard Page (i.e. the Graphs and Lawyers list which is confidential information). Can they be shown a Different Page related to their roles?

**Comment by AAndharia** [comment]
@jmervana  - please take a look at this and discuss with me.

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Lawyer list & other links for 30days, 60days & 90 days should have security but for graph no requirement for this initially. who can show graph?

**Comment by mnarewec** [comment]
What about showing a Blank Page if they do not 'have Dashboard' security permission @jmervana

**Comment by AAndharia** [comment]
@mnarewec  we'll discuss about this once Japan is back, if not major change, we'll do without CR.

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Dashboard security is compulsary but we can add one more permission like dashboard-item-view.
if user has not this permission , user can see only blank page and if user has permission, user can see all the items of dashboard.

**Comment by mnarewec** [comment]
Ok will include as new CR item. Will disregard this time
