### ISSUE TITLE
Bill Generation - Draft and Final Bills Transaction Screen

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#59]
The transaction  screen on the Draft and Final Bills should show the Summarized Totals for Timesheet Entries. There is no need to list the same Lawyers Transactions (Refer Current System). A lawyers transaction should be summarized. Likewise, for Disbursement it really depends on the setup of the disbursement. If it is Summarized then it should be summarized, otherwise it will be detail (Refer current system)

**Comment by AAndharia** [comment]
@jmervana - please take a look at this and discuss with me.

**Comment by jmervana** [comment]
@mnarewec 
need to discuss with you

**Comment by mnarewec** [comment]
Ok Lets discuss today only @jmervana

**Comment by kvora** [comment]
@mnarewec - I have fixed this issue. You will get it in next release.

**Comment by mnarewec** [comment]
@kvora 

This disbursement type is not summarised therefore it it should show the detail. I can see the values are detail but the desription belongs to the type, it should be the individual disbursements description

![image](https://cloud.githubusercontent.com/assets/10192106/5958423/fe24f328-a80f-11e4-99d2-71e4f5b16a45.png)

**Comment by kvora** [comment]
@mnarewec - Done. Sent you release. Please verify and close the ticket.

**Comment by mnarewec** [comment]
This is finally resolved.
