### ISSUE TITLE
Bill Generation - Draft and Final Bills Report

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#60]
The disbursement section of the report should be summarized or shown detailed base on the Disbursement setup. If it is detail, it will use the disbursement description and not the disbursement type description. Refer current system

**Comment by AAndharia** [comment]
@jmervana - please take a look at this and discuss with me.

**Comment by jmervana** [comment]
@mnarewec 
need to discuss with you

**Comment by mnarewec** [comment]
Ok noted @jmervana

**Comment by kvora** [comment]
@mnarewec -  I have fixed this issue. You will get it in next release

**Comment by mnarewec** [comment]
Here still remains
1. Can the On Screen Draft and Final be presentable like other reports?
2. Draft Report should be of the same format as Final except that it will have DRAFT BILL at the top middle
3. Logo missing
4. Have one line separating Taxable Line, Professional Time and Disbursements
![image](https://cloud.githubusercontent.com/assets/10192106/5959357/41b2864c-a819-11e4-8434-77e29abf5f6f.png)
.

**Comment by mnarewec** [comment]
Duplicate Issue. Refer to #69
