### ISSUE TITLE
Search Functionalities For Manage Clients and Manage Files

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#62]
Can the same search feature you did you 'Receipt Bills' search customer, applied to Manage Clients and Manage Files?

**Comment by AAndharia** [comment]
@jmervana - please review this and discuss with me before starting work.

**Comment by jmervana** [comment]
@mnarewec 
in receipt bills , no need to fire query on server side but in Manage File and Manage client we need to fire query on server side.

**Comment by mnarewec** [comment]
@jmervana sorry you lost me here.. why is it that we have to fire query in Manage Client and Files that cannot do that to Receipt Bills.

**Comment by AAndharia** [comment]
@mnarewec  we'll need Japan here to take care of this issue.

**Comment by jmervana** [comment]
@mnarewec 
Sorry marsh , its my misunderstanding with this issue.
Done.

**Comment by mnarewec** [comment]
This is superb. Thank you so much Japan.
