### ISSUE TITLE
**Major Issue ** Disbursement Entry not saving data

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#67]
When entering disbursements after the upgrade (Release 8) it is not saving data. Please check ASAP !!!!

**Comment by kvora** [comment]
@mnarewec - This issue is not reproducible at our end. We will meet tomorrow and go thru this issue using tv.

**Comment by AAndharia** [comment]
@mnarewec  - please ping @kvora  or me our morning tomorrow and we'll take care of this.

**Comment by kvora** [comment]
@mnarewec - Please let me know that the script I sent you yesterday resolve this issue. If yes.. please close this issue.

**Comment by mnarewec** [comment]
Yes this resolves the issue. Closed now
