### ISSUE TITLE
Billing Report - UI & Layout must be exact same as old - see attached

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#68]
Task1
BM Bills.pdf - it is Report UI for previous version
KBS Bills.pdf - it is current Report UI, we need to make it same as BM Bill.pdf

Task2
Additionally, we'll also need footer to appear on each page of pdf.

**Comment by jmervana** [comment]
Done.
Please verify.

**Comment by AAndharia** [comment]
Marsh, this will be sent in today's release. Please review and let us know your feedback.

**Comment by mnarewec** [comment]
Some issues pending
1. Logo Missing
2. Reduce By text is ONLY shown when there is a discount
3. There should be Blank Space (line) Between Taxable and Professional Time and Professional Time and Disbursement Summary
4. Draft Bill should be exactly like Final Bills but it will have the 'DRAFT BILL' in place of file number

![image](https://cloud.githubusercontent.com/assets/10192106/5959743/65e0cea4-a81c-11e4-99e4-766ae9afbc93.png)

**Comment by mnarewec** [comment]
@jmervana ,
Same Issues commented above still pending. Logo is now shown but it is still blurry.

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Done and for logo see #71

**Comment by mnarewec** [comment]
This is done. Thank you.
