### ISSUE TITLE
Client Statement - UI & Layout must be exact same as old - see attached

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#69]
Task1
BM Client Statement.pdf - it is Report UI for previous version
KBS Client Statement.pdf - it is current Report UI, we need to make it same as BM Client Statement.pdf

Task2
Additionally, we'll also need footer to appear on each page of pdf.

**Comment by prupapara** [comment]
In progress,

**Comment by jmervana** [comment]
Done.
Please verify.

**Comment by AAndharia** [comment]
Marsh, this will be sent in today's release. Please review and let us know your feedback.

**Comment by mnarewec** [comment]
The layout has been perfected. Thank you. Some other minor issues will be addressed separately.
