### ISSUE TITLE
File Report - UI & Layout must be exact same as old - see attached

### ISSUE THREAD

**Issue by AAndharia** [AAndharia/PSB#70]
Task1
BM File Report.pdf - it is Report UI for previous version
KBS File Report.pdf - it is current Report UI, we need to make it same as BM File Report.pdf

Task2
Additionally, we'll also need footer to appear on each page of pdf.

**Comment by prupapara** [comment]
Done.
Please Verify.

**Comment by AAndharia** [comment]
Marsh, this will be sent in today's release. Please review and let us know your feedback.

**Comment by mnarewec** [comment]
This is resolved.
