### ISSUE TITLE
Dashboard labels change

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#73]
1. Rename 'Lawyers List' to 'Lawyers WIP Summary'
2. Rename 'Bills Ageing watch list' to 'Aged Outstanding Bills Summary'
3. Rename '12 Monthly Outstanding Bill's Graph (1st Mar 2014 To 31st Jan 2015)' to '12 Monthly Outstanding Bills Graph (Mar 2014 to Jan 2015)'

**Comment by AAndharia** [comment]
@mnarewec - CR estimation in CR sheet, please review, approve and assign back to japan.

**Comment by mnarewec** [comment]
This issue has been resolved
