### ISSUE TITLE
Client Statement - Footer Label

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#75]
Please don't be mad with me now. ;)  Now Change the  footer label to 'Powered By Kumulsoft Billing Solution' the font to be used for the word 'Kumulsoft' must be Century Gothic

**Comment by AAndharia** [comment]
@mnarewec - CR estimation in CR sheet, please review, approve and assign back to japan.

**Comment by mnarewec** [comment]
This has been resolved
