### ISSUE TITLE
Login Page - Change label

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#77]
Please don't be mad with me now. ;)  Now Change the  label 'Kumulsoft  to 'Powered By Kumulsoft Billing Solution' the font to be used for that word 'Kumulsoft' must be Century Gothic. The font size must be 22 (or reasonable)

**Comment by AAndharia** [comment]
@mnarewec - CR estimation in CR sheet, please review, approve and assign back to japan.

**Comment by mnarewec** [comment]
Kumulsoft Billing Solution

**Comment by mnarewec** [comment]
@AAndharia @jmervana the Login page text should be "Kumulsoft Billing Solution" as per my comment on Feb 16

**Comment by AAndharia** [comment]
Yes. @jmervana - isn't this taken care? I think you mentioned it is done.

**Comment by jmervana** [comment]
@AAndharia , I have added powered by kumulsoft billing solution as per 1st comment of this task.
I will change it to "Kumulsoft Billing Solution"

**Comment by mnarewec** [comment]
Resolved. Thanks
