### ISSUE TITLE
Company Setup, logo section - tidy up

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#80]
Please move the logo related fields/function into the section as shown in the image to keep it neat and tidy and together with other company fields.
![image](https://cloud.githubusercontent.com/assets/10192106/5987639/cc8e28f6-a982-11e4-9342-d1451e99ff0f.png)

**Comment by AAndharia** [comment]
@mnarewec - CR estimation in CR sheet, please review, approve and assign back to japan.

**Comment by mnarewec** [comment]
This is tidy now
