### ISSUE TITLE
Draft Bills - Issues 1st Lot

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#81]
As per the labels on image.
1. Logo is blurry 
2. Remove line
3. Remove line
4. Remove Line

![image](https://cloud.githubusercontent.com/assets/10192106/5987670/f1302fa0-a983-11e4-9605-75def576a457.png)

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
2,3,4 are done.
for 1 I gave comments in #71

**Comment by mnarewec** [comment]
This is done. Thank you.
