### ISSUE TITLE
Draft Bills - Issues 2nd Lot

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#82]
As per the image reference
1. Remove Line
2. Remove Label 'Total Timesheet Entry Amount'
3. Remove Line
4. Adjust Overlapping with Footer
5,6,7,8 Remove Line
9. Move Disbursement total up
10. Reduce by text is ONLY printed when their is a discount.

![image](https://cloud.githubusercontent.com/assets/10192106/5987691/059ef7cc-a985-11e4-8096-9bbe96faca0b.png)

**Comment by AAndharia** [comment]
@jmervana  please review and let us discuss.

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Done

**Comment by mnarewec** [comment]
This is done. Thank you.
