### ISSUE TITLE
Draft Bills & Final Bills - Client Address Contact Name related Issues

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#83]
1. In the current Billing system, Contact name is Captured in 'Manage Client' and in 'Manage File'.
During Printing of Draft and Final Bills, If there is a Contact Name in 'Manage File' then that contact name will be used. Otherwise, Contact Name usually comes from 'Manage Client'

2. If there is a comma (,) in the Contact Name, whether from 'Manage Client' or 'Manage File', then it is used to split the Contact Name into different lines. 

For example, we have Contact Name as 'Ms Melissa Jojoga, Manager, Legal & Compliance', 
and Client Name as 'Australia New Zealand Banking Group (PNG) Limited'
and Client Postal Address as 'PO Box 1152, Port Moresby, National Capital District' then the Client Address in the Draft and Final Bills will be like this

Ms Melissa Jojoga
Manager
Legal & Compliance
Australia New Zealand Banking Group (PNG) Limited
PO Box 1152 
Port Moresby 
National Capital District

**Comment by AAndharia** [comment]
@jmervana - please verify existing system, if its exactly same as what's mentioned here, fix the issue else let me know the estimated time in email and we'll have to raise the CR.

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Done.

**Comment by mnarewec** [comment]
This is done. Thank you.
