### ISSUE TITLE
Bill Generation - Rename Label

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#84]
Rename label highlighted below to 'Bill Generation'
![image](https://cloud.githubusercontent.com/assets/10192106/5989559/e539dcc4-a9d7-11e4-9767-12a1465d15f0.png)

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Done.

**Comment by mnarewec** [comment]
This is done. Thank you.
