### ISSUE TITLE
Manage Clients - Active Files Tab

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#85]
Even though the client have so many active files,it is only showing few files.
![image](https://cloud.githubusercontent.com/assets/10192106/5989897/7bc1a4fa-a9e3-11e4-9657-0d67c3f0068a.png)

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Done.

**Comment by mnarewec** [comment]
This is done. Thank you.
