### ISSUE TITLE
Receipt Bills - Client List

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#86]
Client list should only show Clients that have outstanding bills to settle. This is so we avoid users entering blank receipts'

**Comment by AAndharia** [comment]
@jmervana - please review existing system and let me know if this is a CR or not by email.

**Comment by jmervana** [comment]
@AAndharia 
Existing system contains all clients not only those who has bills outstanding.

**Comment by AAndharia** [comment]
@mnarewec - CR estimation in CR sheet, please review, approve and assign back to japan.

**Comment by mnarewec** [comment]
This has been resolved.
