### ISSUE TITLE
**URGENT** DRAFT and FINAL BILLS Issues 2nd Lot

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#88]
I am going over  the Draft and Final Bills again and noticed the following issues. Refer image below

1. The 'C/- P O Box 301' seem to be hard coded. It is not found on the Law Firm's Postal Address. Please remove

2. '... we performed the following' should have a colon (:) at the end of the line.

3. '..consideration throught.' should be ' ..consideration throughout.'

![001](https://cloud.githubusercontent.com/assets/10192106/6074080/e2ba702e-ae02-11e4-818f-6732daca541a.jpg)

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
Done.

**Comment by mnarewec** [comment]
This has been resolved.
