### ISSUE TITLE
Printing Single or All Draft/Final Bills

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#89]
In Billing Manager there is option to view selected Draft Bill or to View All Draft Bills. Like wise the Final Bills. Please enable that feature in KBS

**Comment by mnarewec** [comment]
@AAndharia @jmervana the single print should have the export to PDF button

**Comment by jmervana** [comment]
@AAndharia this will be new requirement , please suggest

**Comment by AAndharia** [comment]
@mnarewec - creating PDF is not small task or else we would have not considered CR. We must have to raise a CR for this. Please suggest.

**Comment by mnarewec** [comment]
ok then disregard this requirement.
