### ISSUE TITLE
**SURE STOPPER** PDF Draft/Final Bills Printing funny characters

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#91]
This is for a different user. When printing Draft or Final PDF, it came up with funny characters on the date column and the various total summary. Please advise if you can connect to the user's PC and check settings, this could happen tomorrow morning (your time)

![image](https://cloud.githubusercontent.com/assets/10192106/6103886/3c2924be-b094-11e4-8491-d6ce096c0820.png)

**Comment by AAndharia** [comment]
@mnarewec  - @jmervana  will be available tomorrow our morning, you can give him Team Viewer access to look into this.

In the mean time, can you please email us both the pdf? You can't attach pdf here in github, just email us.

**Comment by mnarewec** [comment]
This is looking good now, except that the Currency Symbol at the Professional Time Summary, Disbursements and the final totals is not showing.

**Comment by AAndharia** [comment]
@jmervana  - what is status of this?

**Comment by jmervana** [comment]
@AAndharia 
I cannot reproduce it at our side.

**Comment by AAndharia** [comment]
@mnarewec  - please let us know if this is still an issue at your end? This is not happening at our end at all.

**Comment by mnarewec** [comment]
This is related to Twivey lawyers for I kept it open to test it on their site after implementing V1.7

**Comment by mnarewec** [comment]
@AAndharia cc @jmervana , this issue appears again. In place of currency sign on the Bills in its putting a funny character.

**Comment by mnarewec** [comment]
version 1.7.11 resolves this issue
