### ISSUE TITLE
Modify Outstanding Bills Detail to Include Batch Selection

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#92]
Previously there used to be a outstanding Bills by batch report but it was not upgraded because I said so thinking that the 'Outstanding Bills Detail' is the same thing... Now I want a Batch Selection because it is useful to ran that report after the batch is generated. Additionally below the heading of the report, you need to show the text 'Selected Batche(s):' and it will be ALL if all batches are selected, however, if one or more than show the description of the selected batch

**Comment by AAndharia** [comment]
@jmervana - please estimate effort required for this CR and let me know.

**Comment by mnarewec** [comment]
I am unable to select multiple batches here. I was hoping you would give me something like the Client Statement  (i.e. pop up to select batches)

**Comment by AAndharia** [comment]
Ok. @jmervana - please do this.

**Comment by mnarewec** [comment]
This has been resolved.
