### ISSUE TITLE
Manage Files : Changes to logic of creating and saving file

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#93]
(A) This is an additional logic for File Number: When creating a new file,the year part of file number must come from the instruction date and the number part will be the next number in that year. That means, when updating the file, Current File Numbers will not change but they will have to update the Instructed Date. Additionally, when they want want to enter file number of previous years they can, especially at the time of initial installation.

(B) also give selection to format file to also ignore the dash "-".

**Comment by AAndharia** [comment]
in #93 , when user will update file at that time, if instructed date will not changed by user, what should be do?

1. give confirmation to user that your file number will change as per instructed
    date& if user press OK then update file number from instructed date.
2. give message that you have to change instructed date as per file number.

**Comment by mnarewec** [comment]
2, give message that you have to change instructed date as per file number.

**Comment by mnarewec** [comment]
@AAndharia @jmervana I thought this will be release with Twivey Requirements??

**Comment by AAndharia** [comment]
@mnarewec - this was not part of Twivey Requirements, you have approved this in seperated spreadhseet of CR too.

**Comment by mnarewec** [comment]
ok, was trying to add a new file and when submitting it, it gives me the following error
![image](https://cloud.githubusercontent.com/assets/10192106/7250977/0a2ca68a-e86a-11e4-8852-9fcdc09be4db.png)

**Comment by jmervana** [comment]
@mnarewec 
I cannot reproduce this error.

**Comment by mnarewec** [comment]
(A) Add new file - Following is the trace issue of the error
![image](https://cloud.githubusercontent.com/assets/10192106/7264154/07a9cb6a-e8cc-11e4-9593-f1624d90827d.png)

(B) The File Format does not have the option to remove dash (-)

**Comment by jmervana** [comment]
@mnarewec , cc @AAndharia 
remove dash from the file format is in system default page so it is included in CR7

**Comment by AAndharia** [comment]
@mnarewec  -  can you please show this to Japan on your developer machine?

**Comment by mnarewec** [comment]
This is resolved.
