### ISSUE TITLE
Bills (Draft/Final) - Entries are not appearing as they entered

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#95]
This is a bug. The time sheet entries appearing on the Bills are not sorted correctly. They should be sorted as By Entry Date, and then by how it is entered (Entry Id). Currently it is sorted as Entry Date, and then by description.

Please rectify immediately.

**Comment by mnarewec** [comment]
This issue is not resolved. Please I need immediate fix on that
@jmervana @AAndharia

**Comment by AAndharia** [comment]
@jmervana  - please take care of this immediately.

**Comment by mnarewec** [comment]
This has been resolved.
