### ISSUE TITLE
KBS Version Number Labels

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#96]
Now that we have a well define version numbers, I would like it display in on the system so we can easily identify which version a client is running.

(1) Place in on the Login Screen
![image](https://cloud.githubusercontent.com/assets/10192106/7264278/60997012-e8cd-11e4-8408-6639e42b07a4.png)

(2) Place in on the footer of the main application so that it can appear on all pages.

**Comment by AAndharia** [comment]
@jmervana Japan, please implement this. and make sure every release you send from now onwards, you change this according to actual version number.

@mnarewec  - not considering this as CR
