### ISSUE TITLE
"In the company setup page create a new section called ‘Bank Details’

### ISSUE THREAD

**Issue by jmervana** [AAndharia/PSB#97]
no special validation. all fields are nullable and max length 50 

Bank Account Name
Bank Account Number
Bank Name
BSB Code
Swift Code

**Comment by mnarewec** [comment]
Please move the Bank address text box to the right, and expand the text size so it can capture and display three lines.

![image](https://cloud.githubusercontent.com/assets/10192106/7668015/9772fada-fc65-11e4-817a-460f51ed898f.png)

**Comment by jmervana** [comment]
@mnarewec 
Done

**Comment by mnarewec** [comment]
Confirmed done.
