### ISSUE TITLE
**URGENT** Bill Generation - Randomly some Printed Bills total amount does not Match System Total and Outstanding Amounts

### ISSUE THREAD

**Issue by mnarewec** [AAndharia/PSB#99]
I got some users reported their PRINTED final bills total does not match the system's outstanding amount. Therefore, it makes it difficult for them to receipt. For the same bills when I do the re-prints the total amount matched. But its too late because the user already passed on these bills to client and they made cheque to that amount.

After carefully analysing one of the Bills I noticed that the First Bill did not print the last line of the Bill therefore the calculation of the total is less the last line of the Bill.

**Comment by AAndharia** [comment]
@jmervana -please fix this with the highest priority.

**Comment by mnarewec** [comment]
This is not resolved. I will close this issue but refer to issue #

**Comment by mnarewec** [comment]
This is not resolved. I will close this issue but refer to issue #121
